#!/usr/bin/env python3
"""SCBE Playwright Ops Extension Runner.

Combines:
- hydra-node-terminal-browsing evidence capture (Node script)
- Playwright capture via scripts/agentic_web_tool.py
- optional cross-talk emission via scripts/system/crosstalk_relay.py
- agent handoff markdown packaging

This is intentionally deterministic and artifact-first.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional


@dataclass
class CommandResult:
    command: List[str]
    returncode: int
    stdout: str
    stderr: str


def _utc_stamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[3]


def _run(command: List[str], cwd: Path) -> CommandResult:
    proc = subprocess.run(command, cwd=str(cwd), capture_output=True, text=True)
    return CommandResult(
        command=command,
        returncode=proc.returncode,
        stdout=proc.stdout.strip(),
        stderr=proc.stderr.strip(),
    )


def _json_or_none(path: Path) -> Optional[Dict[str, Any]]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None


def _newest_json(path: Path) -> Optional[Path]:
    candidates = sorted(path.glob("*.json"), key=lambda p: p.stat().st_mtime, reverse=True)
    return candidates[0] if candidates else None


def _write_handoff(
    path: Path,
    task_id: str,
    url: str,
    summary: str,
    files_touched: List[Path],
    crosstalk_packet_id: str,
) -> None:
    lines = [
        f"# Handoff: {task_id}",
        "",
        "## Status",
        "- Current phase: packaged",
        "- Completion: deterministic browse + playwright capture + handoff bundle emitted",
        "",
        "## Context",
        f"- URL: {url}",
        f"- Summary: {summary}",
        f"- Cross-talk packet: {crosstalk_packet_id or 'not_emitted'}",
        "",
        "## Files Touched",
    ]
    for touched in files_touched:
        lines.append(f"- {touched.as_posix()} - generated by extension runner")
    lines.extend(
        [
            "",
            "## Open Questions",
            "- Should this run be mirrored to Notion via connector automation?",
            "- Should this lane become default for HYDRA research tasks?",
            "",
            "## Next Steps",
            "- Verify evidence JSON contents and screenshot quality.",
            "- ACK cross-talk packet if receiving lane consumed artifacts.",
            "- Re-run with new URL/topic as needed.",
        ]
    )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _parse_packet_id(stdout: str) -> str:
    try:
        payload = json.loads(stdout)
    except Exception:
        return ""
    return str(payload.get("packet_id", ""))


def _speed_line(path: Path, repo_root: Path, url: str, out_dir: Path) -> None:
    rel_script = Path("skills/scbe-playwright-ops-extension/scripts/playwright_extension_runner.py")
    content = [
        "Objective: Run deterministic browse + Playwright capture + handoff in one command",
        "Lane: [CHAT]",
        "Command:",
        f"python {rel_script.as_posix()} --url \"{url}\" --output-dir \"{out_dir.as_posix()}\" --task-id \"PWX-DEMO\" --summary \"Playwright extension demo\"",
        "Success signal: run_report.json exists and includes browse/playwright command status",
        "",
        "Objective: Verify generated run report quickly",
        "Lane: [OPS]",
        "Command:",
        f"python -c \"import json, pathlib; p=pathlib.Path(r'{out_dir.as_posix()}')/'run_report.json'; print(json.loads(p.read_text(encoding='utf-8'))['status'])\"",
        "Success signal: prints OK",
    ]
    path.write_text("\n".join(content) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="SCBE Playwright ops extension runner")
    parser.add_argument("--url", required=True, help="Target URL for browse/capture")
    parser.add_argument("--task-id", default="", help="Cross-talk and handoff task id")
    parser.add_argument("--summary", default="Playwright extension run", help="Run summary")
    parser.add_argument("--sender", default="agent.codex", help="Cross-talk sender")
    parser.add_argument("--recipient", default="agent.claude", help="Cross-talk recipient")
    parser.add_argument("--intent", default="handoff", help="Cross-talk intent")
    parser.add_argument("--output-dir", default="artifacts/playwright_extension", help="Output directory")
    parser.add_argument("--engine", default="playwright", choices=["auto", "playwright", "http"], help="Capture engine")
    parser.add_argument("--skip-crosstalk", action="store_true", help="Skip cross-talk emit")
    parser.add_argument("--skip-node-browse", action="store_true", help="Skip hydra terminal browse packet")
    parser.add_argument("--emit-notion-payload", action="store_true", help="Write a Notion create-page payload artifact")
    parser.add_argument("--notion-parent-page-id", default="", help="Optional Notion parent page ID for payload")
    parser.add_argument(
        "--browse-script",
        default=r"C:\Users\issda\.codex\skills\hydra-node-terminal-browsing\scripts\hydra_terminal_browse.mjs",
        help="Path to hydra terminal browse script",
    )
    args = parser.parse_args()

    repo_root = _repo_root()
    output_dir = (repo_root / args.output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    browse_json = output_dir / "terminal_browse.json"
    play_out_dir = output_dir / "playwright_capture"
    play_out_dir.mkdir(parents=True, exist_ok=True)
    handoff_md = output_dir / "handoff.md"
    run_report = output_dir / "run_report.json"
    speed_line_txt = output_dir / "speed_lines.txt"
    notion_payload_json = output_dir / "notion_payload.json"

    task_id = args.task_id or f"PWX-{_utc_stamp()}"

    command_log: Dict[str, Dict[str, Any]] = {}
    touched: List[Path] = []

    # 1) hydra-node-terminal-browsing packet
    if not args.skip_node_browse:
        browse_script = Path(args.browse_script)
        if browse_script.exists() and shutil.which("node"):
            browse_cmd = ["node", str(browse_script), "--url", args.url, "--out", str(browse_json)]
            browse_res = _run(browse_cmd, repo_root)
            command_log["terminal_browse"] = {
                "command": browse_res.command,
                "returncode": browse_res.returncode,
                "stdout": browse_res.stdout,
                "stderr": browse_res.stderr,
            }
            if browse_res.returncode == 0 and browse_json.exists():
                touched.append(browse_json)
        else:
            command_log["terminal_browse"] = {
                "command": ["node", str(browse_script), "--url", args.url, "--out", str(browse_json)],
                "returncode": 127,
                "stdout": "",
                "stderr": "node or browse script not available",
            }

    # 2) Playwright capture via local script
    capture_cmd = [
        sys.executable,
        "scripts/agentic_web_tool.py",
        "--engine",
        args.engine,
        "--output-dir",
        str(play_out_dir),
        "capture",
        "--url",
        args.url,
    ]
    capture_res = _run(capture_cmd, repo_root)
    command_log["playwright_capture"] = {
        "command": capture_res.command,
        "returncode": capture_res.returncode,
        "stdout": capture_res.stdout,
        "stderr": capture_res.stderr,
    }
    capture_json = _newest_json(play_out_dir)
    if capture_json is not None:
        touched.append(capture_json)

    # 3) Optional cross-talk emission
    crosstalk_packet_id = ""
    if not args.skip_crosstalk:
        proof_args: List[str] = []
        for proof in touched:
            proof_args.extend(["--proof", str(proof)])
        relay_cmd = [
            sys.executable,
            "scripts/system/crosstalk_relay.py",
            "emit",
            "--sender",
            args.sender,
            "--recipient",
            args.recipient,
            "--intent",
            args.intent,
            "--task-id",
            task_id,
            "--summary",
            args.summary,
            "--status",
            "in_progress",
            "--next-action",
            "Verify artifacts and ACK if consumed",
        ] + proof_args
        relay_res = _run(relay_cmd, repo_root)
        crosstalk_packet_id = _parse_packet_id(relay_res.stdout)
        command_log["crosstalk_emit"] = {
            "command": relay_res.command,
            "returncode": relay_res.returncode,
            "stdout": relay_res.stdout,
            "stderr": relay_res.stderr,
            "packet_id": crosstalk_packet_id,
        }

    # 4) Agent handoff artifact
    _write_handoff(
        path=handoff_md,
        task_id=task_id,
        url=args.url,
        summary=args.summary,
        files_touched=touched,
        crosstalk_packet_id=crosstalk_packet_id,
    )
    touched.append(handoff_md)

    # 5) Speed-line instructions artifact
    _speed_line(speed_line_txt, repo_root, args.url, output_dir)
    touched.append(speed_line_txt)

    # 6) Optional Notion payload artifact
    if args.emit_notion_payload:
        title = f"Playwright Extension Run {task_id}"
        notion_payload = {
            "parent": {"page_id": args.notion_parent_page_id or "REPLACE_WITH_PAGE_ID"},
            "properties": {
                "title": [
                    {
                        "text": {
                            "content": title,
                        }
                    }
                ]
            },
            "children": [
                {
                    "type": "paragraph",
                    "paragraph": {
                        "rich_text": [
                            {
                                "type": "text",
                                "text": {
                                    "content": f"Task: {task_id} | URL: {args.url} | Summary: {args.summary}",
                                },
                            }
                        ]
                    },
                },
                {
                    "type": "paragraph",
                    "paragraph": {
                        "rich_text": [
                            {
                                "type": "text",
                                "text": {
                                    "content": f"Artifacts: {', '.join(str(p) for p in touched)}",
                                },
                            }
                        ]
                    },
                },
            ],
        }
        notion_payload_json.write_text(json.dumps(notion_payload, indent=2), encoding="utf-8")
        touched.append(notion_payload_json)

    status = "OK"
    failed = [k for k, v in command_log.items() if int(v.get("returncode", 1)) != 0]
    if failed:
        status = "PARTIAL"

    report = {
        "status": status,
        "task_id": task_id,
        "url": args.url,
        "summary": args.summary,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "commands": command_log,
        "artifacts": [str(p) for p in touched],
    }
    run_report.write_text(json.dumps(report, indent=2), encoding="utf-8")

    print(json.dumps(report, indent=2))
    return 0 if status == "OK" else 2


if __name__ == "__main__":
    raise SystemExit(main())
