# GitHub Sponsors
github: issdandavis

# Other platforms (uncomment and add your usernames when ready)
# patreon: your-patreon-username
# ko_fi: your-kofi-username
# buy_me_a_coffee: your-bmac-username
# custom: ["https://your-custom-donation-link.com"]
