#!/usr/bin/env python3
"""
SCBE-AETHERMOORE Provider Setup
One-click configuration for AI providers

Usage:
  python setup-providers.py           # Interactive setup
  python setup-providers.py --quick   # Quick setup with prompts
  python setup-providers.py --check   # Check current configuration
"""

import os
import sys
from pathlib import Path
from getpass import getpass

PROVIDERS = {
    "anthropic": {
        "name": "Anthropic (Claude)",
        "key_var": "ANTHROPIC_API_KEY",
        "model_var": "ANTHROPIC_MODEL",
        "default_model": "claude-sonnet-4-20250514",
        "key_prefix": "sk-ant-",
        "url": "https://console.anthropic.com/settings/keys",
    },
    "openai": {
        "name": "OpenAI (GPT-4)",
        "key_var": "OPENAI_API_KEY",
        "model_var": "OPENAI_MODEL",
        "default_model": "gpt-4o",
        "key_prefix": "sk-",
        "url": "https://platform.openai.com/api-keys",
    },
    "google": {
        "name": "Google (Gemini)",
        "key_var": "GOOGLE_API_KEY",
        "model_var": "GOOGLE_MODEL",
        "default_model": "gemini-2.0-flash",
        "key_prefix": "AIza",
        "url": "https://aistudio.google.com/app/apikey",
    },
    "mistral": {
        "name": "Mistral",
        "key_var": "MISTRAL_API_KEY",
        "model_var": "MISTRAL_MODEL",
        "default_model": "mistral-large-latest",
        "key_prefix": "",
        "url": "https://console.mistral.ai/api-keys",
    },
    "cohere": {
        "name": "Cohere",
        "key_var": "COHERE_API_KEY",
        "model_var": "COHERE_MODEL",
        "default_model": "command-r-plus",
        "key_prefix": "",
        "url": "https://dashboard.cohere.com/api-keys",
    },
}

ENV_FILE = Path(__file__).parent / ".env"
ENV_EXAMPLE = Path(__file__).parent / ".env.example"


def print_banner():
    print("""
╔═══════════════════════════════════════════════════════════╗
║        SCBE-AETHERMOORE Provider Setup                    ║
║        One-click configuration for AI providers           ║
╚═══════════════════════════════════════════════════════════╝
    """)


def load_env():
    """Load existing .env file"""
    env = {}
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, _, value = line.partition("=")
                env[key.strip()] = value.strip()
    return env


def save_env(env):
    """Save .env file"""
    lines = [
        "# SCBE-AETHERMOORE Configuration",
        "# Generated by setup-providers.py",
        "",
    ]

    # Provider priority
    priority = env.get("SCBE_PROVIDER_PRIORITY", "anthropic,openai,google")
    lines.append(f"SCBE_PROVIDER_PRIORITY={priority}")
    lines.append("")

    # Provider keys
    for provider_id, info in PROVIDERS.items():
        key = env.get(info["key_var"], "")
        if key:
            lines.append(f"# {info['name']}")
            lines.append(f"{info['key_var']}={key}")
            lines.append(f"{info['model_var']}={env.get(info['model_var'], info['default_model'])}")
            lines.append("")

    # Provider behavior
    lines.append("# Provider behavior")
    lines.append(f"SCBE_PROVIDER_FALLBACK_ENABLED={env.get('SCBE_PROVIDER_FALLBACK_ENABLED', 'true')}")
    lines.append(f"SCBE_PROVIDER_MAX_RETRIES={env.get('SCBE_PROVIDER_MAX_RETRIES', '2')}")
    lines.append(f"SCBE_PROVIDER_TIMEOUT_MS={env.get('SCBE_PROVIDER_TIMEOUT_MS', '30000')}")
    lines.append("")

    # Other config (preserve existing)
    other_keys = [
        "SCBE_ENV", "SCBE_KMS_KID", "SCBE_KMS_URI",
        "REDIS_URL", "REDIS_PASSWORD",
        "SCBE_METRICS_BACKEND", "SCBE_API_KEYS", "SCBE_CORS_ORIGINS"
    ]
    has_other = False
    for key in other_keys:
        if key in env:
            if not has_other:
                lines.append("# Other configuration")
                has_other = True
            lines.append(f"{key}={env[key]}")

    ENV_FILE.write_text("\n".join(lines) + "\n")
    print(f"\n✓ Saved to {ENV_FILE}")


def check_status():
    """Check current provider configuration"""
    env = load_env()

    print("\n🤖 AI Provider Status")
    print("=" * 60)

    priority = env.get("SCBE_PROVIDER_PRIORITY", "anthropic,openai,google")
    print(f"Priority: {priority}\n")

    print(f"{'Provider':<20} {'Status':<15} {'Model'}")
    print("-" * 60)

    for provider_id, info in PROVIDERS.items():
        key = env.get(info["key_var"], "")
        model = env.get(info["model_var"], info["default_model"])

        if key and len(key) > 10 and "..." not in key:
            status = "✓ Connected"
            masked = key[:8] + "..." + key[-4:] if len(key) > 12 else "***"
        else:
            status = "○ Not set"
            masked = ""

        print(f"{info['name']:<20} {status:<15} {model}")

    print()


def setup_provider(provider_id, env):
    """Setup a single provider"""
    info = PROVIDERS[provider_id]

    print(f"\n--- {info['name']} ---")
    print(f"Get your API key: {info['url']}")

    current = env.get(info["key_var"], "")
    if current and len(current) > 10:
        masked = current[:8] + "..." + current[-4:]
        print(f"Current: {masked}")
        change = input("Change? [y/N]: ").strip().lower()
        if change != "y":
            return

    key = getpass(f"Enter API key (or press Enter to skip): ").strip()

    if key:
        env[info["key_var"]] = key
        env[info["model_var"]] = info["default_model"]
        print(f"✓ {info['name']} configured")
    else:
        print(f"○ Skipped {info['name']}")


def interactive_setup():
    """Interactive setup wizard"""
    print_banner()

    env = load_env()

    print("Which providers would you like to configure?\n")
    print("  1. Anthropic (Claude) - Recommended")
    print("  2. OpenAI (GPT-4)")
    print("  3. Google (Gemini)")
    print("  4. Mistral")
    print("  5. Cohere")
    print("  A. All providers")
    print("  Q. Quit\n")

    choice = input("Select [1/2/3/4/5/A/Q]: ").strip().upper()

    if choice == "Q":
        return

    provider_map = {
        "1": ["anthropic"],
        "2": ["openai"],
        "3": ["google"],
        "4": ["mistral"],
        "5": ["cohere"],
        "A": list(PROVIDERS.keys()),
    }

    providers = provider_map.get(choice, ["anthropic"])

    for provider_id in providers:
        setup_provider(provider_id, env)

    # Set priority
    connected = [p for p in PROVIDERS if env.get(PROVIDERS[p]["key_var"])]
    if connected:
        print(f"\n--- Priority Order ---")
        print(f"Current priority: {env.get('SCBE_PROVIDER_PRIORITY', 'anthropic,openai,google')}")
        print(f"Connected providers: {', '.join(connected)}")

        new_priority = input(f"New priority (comma-separated) [{','.join(connected)}]: ").strip()
        if new_priority:
            env["SCBE_PROVIDER_PRIORITY"] = new_priority
        else:
            env["SCBE_PROVIDER_PRIORITY"] = ",".join(connected)

    save_env(env)
    check_status()


def quick_setup():
    """Quick setup - just prompts for keys"""
    print_banner()
    print("Quick Setup - Enter API keys (press Enter to skip)\n")

    env = load_env()

    for provider_id, info in PROVIDERS.items():
        key = getpass(f"{info['name']}: ").strip()
        if key:
            env[info["key_var"]] = key
            env[info["model_var"]] = info["default_model"]

    connected = [p for p in PROVIDERS if env.get(PROVIDERS[p]["key_var"])]
    if connected:
        env["SCBE_PROVIDER_PRIORITY"] = ",".join(connected)

    save_env(env)
    check_status()


def main():
    import argparse

    parser = argparse.ArgumentParser(description="SCBE Provider Setup")
    parser.add_argument("--quick", action="store_true", help="Quick setup mode")
    parser.add_argument("--check", action="store_true", help="Check current status")
    args = parser.parse_args()

    if args.check:
        check_status()
    elif args.quick:
        quick_setup()
    else:
        interactive_setup()


if __name__ == "__main__":
    main()
