'use strict';

// GENERATED by scripts/vercel/generate-router.cjs — edit that, not this.
//
// One Vercel function for the whole /api/agent lane. The Hobby plan allows 12
// serverless functions per deployment; building every handler as its own function
// put this repo at 58 and made every deploy fail at the plan gate. vercel.json
// routes now land here with ?fn=<name> and the map below dispatches in-process.
//
// The map is literal require calls ON PURPOSE: the bundler traces static requires
// to decide which files ship inside the lambda. A require(variable) would deploy a
// router with nothing behind it. Lazy thunks keep one broken handler from taking
// down the rest of the lane at require time.

const HANDLERS = {
  agents: () => require('./agents.js'),
  'ai-chemistry-set': () => require('./ai-chemistry-set.js'),
  'ai-chemistry-set-page': () => require('./ai-chemistry-set-page.js'),
  'ai-materials-bench': () => require('./ai-materials-bench.js'),
  'ai-materials-bench-page': () => require('./ai-materials-bench-page.js'),
  'ai-waves-lab': () => require('./ai-waves-lab.js'),
  'ai-waves-lab-page': () => require('./ai-waves-lab-page.js'),
  'app-config': () => require('./app-config.js'),
  'app-config-file': () => require('./app-config-file.js'),
  'atomic-lab': () => require('./atomic-lab.js'),
  'atomic-lab-page': () => require('./atomic-lab-page.js'),
  chat: () => require('./chat.js'),
  'chat-page': () => require('./chat-page.js'),
  dispatch: () => require('./dispatch.js'),
  download: () => require('./download.js'),
  'geoseal-hermes': () => require('./geoseal-hermes.js'),
  'geoseal-hermes-page': () => require('./geoseal-hermes-page.js'),
  'governance-snapshot': () => require('./governance-snapshot.js'),
  'governed-chat': () => require('./governed-chat.js'),
  health: () => require('./health.js'),
  hire: () => require('./hire.js'),
  'hire-b': () => require('./hire-b.js'),
  'hosted-run': () => require('./hosted-run.js'),
  launch: () => require('./launch.js'),
  'legal-privacy': () => require('./legal-privacy.js'),
  'legal-terms': () => require('./legal-terms.js'),
  llms: () => require('./llms.js'),
  offers: () => require('./offers.js'),
  'offers-file': () => require('./offers-file.js'),
  payments: () => require('./payments.js'),
  products: () => require('./products.js'),
  'robot-md': () => require('./robot-md.js'),
  'robot-page': () => require('./robot-page.js'),
  robots: () => require('./robots.js'),
  runs: () => require('./runs.js'),
  search: () => require('./search.js'),
  'service-credits': () => require('./service-credits.js'),
  'service-fast-start': () => require('./service-fast-start.js'),
  'shopify-command-center': () => require('./shopify-command-center.js'),
  sitemap: () => require('./sitemap.js'),
  solutions: () => require('./solutions.js'),
  'start-here': () => require('./start-here.js'),
  static: () => require('./static.js'),
  status: () => require('./status.js'),
  storage: () => require('./storage.js'),
  supporter: () => require('./supporter.js'),
  system: () => require('./system.js'),
  'workflow-snapshot': () => require('./workflow-snapshot.js'),
};

module.exports = async function router(req, res) {
  const candidates = [];
  const queryValue = req.query && req.query.fn;
  if (Array.isArray(queryValue)) {
    candidates.push(...queryValue);
  } else if (typeof queryValue === 'string') {
    candidates.push(queryValue);
  }
  try {
    candidates.push(...new URL(req.url, 'http://router.internal').searchParams.getAll('fn'));
  } catch (_err) {
    // Vercel normally supplies req.query; malformed local mock URLs may not.
  }
  const fn =
    candidates.find(
      (candidate) =>
        typeof candidate === 'string' && Object.prototype.hasOwnProperty.call(HANDLERS, candidate)
    ) || '';
  if (!Object.prototype.hasOwnProperty.call(HANDLERS, fn)) {
    // Everything in the map was already directly routable before consolidation, so the
    // router adds no new surface; anything else was a 404 then and stays one now.
    res.statusCode = 404;
    res.setHeader('content-type', 'application/json; charset=utf-8');
    res.end(JSON.stringify({ error: 'not_found', lane: 'agent' }));
    return;
  }
  const handler = HANDLERS[fn]();
  if (typeof handler !== 'function') {
    throw new TypeError(`api/agent/${fn}.js does not export a request handler`);
  }
  return handler(req, res);
};
