'use strict';

// GENERATED by scripts/vercel/generate-router.cjs — edit that, not this.
//
// One Vercel function for the whole /api/polly lane. The Hobby plan allows 12
// serverless functions per deployment; building every handler as its own function
// put this repo at 58 and made every deploy fail at the plan gate. vercel.json
// routes now land here with ?fn=<name> and the map below dispatches in-process.
//
// The map is literal require calls ON PURPOSE: the bundler traces static requires
// to decide which files ship inside the lambda. A require(variable) would deploy a
// router with nothing behind it. Lazy thunks keep one broken handler from taking
// down the rest of the lane at require time.

const HANDLERS = {
  catalog: () => require('./catalog.js'),
  chat: () => require('./chat.js'),
  feedback: () => require('./feedback.js'),
  funnel: () => require('./funnel.js'),
  'hosted-run': () => require('./hosted-run.js'),
  lead: () => require('./lead.js'),
  stats: () => require('./stats.js'),
};

module.exports = async function router(req, res) {
  const candidates = [];
  const queryValue = req.query && req.query.fn;
  if (Array.isArray(queryValue)) {
    candidates.push(...queryValue);
  } else if (typeof queryValue === 'string') {
    candidates.push(queryValue);
  }
  try {
    candidates.push(...new URL(req.url, 'http://router.internal').searchParams.getAll('fn'));
  } catch (_err) {
    // Vercel normally supplies req.query; malformed local mock URLs may not.
  }
  const fn =
    candidates.find(
      (candidate) =>
        typeof candidate === 'string' && Object.prototype.hasOwnProperty.call(HANDLERS, candidate)
    ) || '';
  if (!Object.prototype.hasOwnProperty.call(HANDLERS, fn)) {
    // Everything in the map was already directly routable before consolidation, so the
    // router adds no new surface; anything else was a 404 then and stays one now.
    res.statusCode = 404;
    res.setHeader('content-type', 'application/json; charset=utf-8');
    res.end(JSON.stringify({ error: 'not_found', lane: 'polly' }));
    return;
  }
  const handler = HANDLERS[fn]();
  if (typeof handler !== 'function') {
    throw new TypeError(`api/polly/${fn}.js does not export a request handler`);
  }
  return handler(req, res);
};
