from __future__ import annotations

from typing import List

from .models import PrismFunction, PrismModule

LANG_ALIASES = {
    "ts": "typescript",
    "js": "typescript",
    "javascript": "typescript",
    "rs": "rust",
    "jl": "julia",
    "hs": "haskell",
    "golang": "go",
}


def _lang(target_language: str) -> str:
    lang = target_language.lower()
    return LANG_ALIASES.get(lang, lang)


def _py_signature(fn: PrismFunction) -> str:
    args = ", ".join(fn.args)
    suffix = f" -> {fn.returns}" if fn.returns else ""
    return f"def {fn.name}({args}){suffix}:"


def emit_python(module: PrismModule) -> str:
    out: List[str] = ['"""Generated by Code Prism."""', ""]
    for fn in module.functions:
        out.append(_py_signature(fn))
        if fn.docstring:
            out.append(f'    """{fn.docstring}"""')
        for line in fn.body:
            out.append(f"    {line}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def _ts_signature(fn: PrismFunction) -> str:
    args = ", ".join(f"{arg}: any" for arg in fn.args)
    ret = _ts_type(fn.returns)
    return f"export function {fn.name}({args}): {ret} {{"


def _ts_type(type_name: str | None) -> str:
    if not type_name:
        return "any"
    normalised = type_name.strip().lower()
    if normalised in {"int", "float", "number"}:
        return "number"
    if normalised in {"str", "string"}:
        return "string"
    if normalised in {"bool", "boolean"}:
        return "boolean"
    if normalised in {"none", "void"}:
        return "void"
    return type_name


def _ts_floor_division(expr: str) -> str:
    """Rewrite Python floor division ``a // b`` to JS ``Math.floor(a / b)``.

    In JavaScript/TypeScript a bare ``//`` begins a line comment, so emitting a
    Python floor-division operator verbatim silently truncates the statement and
    the function returns only the left operand (e.g. ``return a // b;`` behaves
    like ``return a;``). Rewriting keeps the emitted code behaviourally faithful.

    Only the floor-division OPERATOR is rewritten: a ``//`` inside a string literal
    (e.g. ``return "a // b"``) is left untouched, and chained ``a // b // c`` is
    rewritten left-associatively to match Python semantics.
    """
    # Scan for space-delimited ``//`` operators that are NOT inside a string literal.
    quote = None
    ops: List[int] = []
    i = 0
    while i < len(expr):
        c = expr[i]
        if quote is not None:
            if c == "\\":
                i += 2
                continue
            if c == quote:
                quote = None
        elif c in ("'", '"'):
            quote = c
        elif c == "/" and expr[i : i + 2] == "//":
            if i > 0 and expr[i - 1] == " " and expr[i + 2 : i + 3] == " ":
                ops.append(i)
            i += 2
            continue
        i += 1
    if not ops:
        return expr
    # Left-associative (a // b // c == (a // b) // c): split at the LAST operator.
    op = ops[-1]
    left = expr[:op].rstrip()
    right = expr[op + 2 :].strip()
    return f"Math.floor(({_ts_floor_division(left)}) / ({right}))"


def _ts_body_line(line: str) -> str:
    stripped = line.strip()
    if not stripped or stripped == "pass":
        return "// no-op"
    if stripped.startswith("return "):
        expr = _ts_floor_division(stripped[len("return ") :].strip())
        return f"return {expr};"
    if "=" in stripped and "==" not in stripped and not stripped.startswith(("const ", "let ", "var ")):
        name, value = stripped.split("=", 1)
        return f"const {name.strip()} = {_ts_floor_division(value.strip())};"
    stripped = _ts_floor_division(stripped)
    return stripped if stripped.endswith(";") else f"{stripped};"


def emit_typescript(module: PrismModule) -> str:
    out: List[str] = ["// Generated by Code Prism.", ""]
    for fn in module.functions:
        out.append(_ts_signature(fn))
        if fn.docstring:
            out.append(f"  // {fn.docstring}")
        if fn.body:
            for line in fn.body:
                out.append(f"  {_ts_body_line(line)}")
        else:
            out.append("  // no-op")
        out.append("}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def _go_type(fn: PrismFunction) -> str:
    if fn.returns:
        normalised = fn.returns.strip().lower()
        if normalised in {"int", "float", "number"}:
            return "float64"
        if normalised in {"str", "string"}:
            return "string"
        if normalised in {"bool", "boolean"}:
            return "bool"
        if normalised in {"none", "void"}:
            return ""
    arithmetic_markers = (" + ", " - ", " * ", " / ")
    if any(any(op in line for op in arithmetic_markers) for line in fn.body):
        return "float64"
    return "interface{}"


def _go_signature(fn: PrismFunction) -> str:
    ret = _go_type(fn)
    arg_type = ret or "interface{}"
    args = ", ".join(f"{arg} {arg_type}" for arg in fn.args)
    suffix = f" {ret}" if ret else ""
    return f"func {fn.name.title()}({args}){suffix} {{"


def _go_zero_value(type_name: str) -> str:
    if type_name == "float64":
        return "0"
    if type_name == "string":
        return '""'
    if type_name == "bool":
        return "false"
    return "nil"


def _go_body_line(line: str) -> str:
    stripped = line.strip()
    if not stripped or stripped == "pass":
        return "// no-op"
    if stripped.startswith("return "):
        return stripped
    for keyword in ("const ", "let ", "var "):
        if stripped.startswith(keyword):
            stripped = stripped[len(keyword) :].strip()
            break
    if "=" in stripped and "==" not in stripped and ":=" not in stripped:
        name, value = stripped.split("=", 1)
        return f"{name.strip()} := {value.strip()}"
    if stripped.startswith("//"):
        return stripped
    return f"// unsupported safe-subset statement: {stripped}"


def emit_go(module: PrismModule) -> str:
    out: List[str] = [
        "// Generated by Code Prism.",
        "package prism",
        "",
    ]
    for fn in module.functions:
        ret_type = _go_type(fn)
        out.append(_go_signature(fn))
        if fn.docstring:
            out.append(f"    // {fn.docstring}")
        emitted_return = False
        for line in fn.body:
            go_line = _go_body_line(line)
            if go_line.startswith("return "):
                emitted_return = True
            out.append(f"    {go_line}")
        if not emitted_return and ret_type:
            out.append(f"    return {_go_zero_value(ret_type)}")
        out.append("}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def _rust_type(type_name: str | None = None) -> str:
    if not type_name:
        return "f64"
    normalised = type_name.strip().lower()
    if normalised in {"int", "integer", "number", "float", "double", "f64", "i32", "i64"}:
        return "f64"
    if normalised in {"str", "string", "&str"}:
        return "String"
    if normalised in {"bool", "boolean"}:
        return "bool"
    if normalised in {"none", "void", "()"}:
        return "()"
    return "f64"


def _rust_signature(fn: PrismFunction) -> str:
    ret = _rust_type(fn.returns)
    args = ", ".join(f"{arg}: {_rust_type(fn.returns)}" for arg in fn.args)
    return f"pub fn {fn.name}({args}) -> {ret} {{"


def _rust_body_line(line: str) -> str:
    stripped = line.strip()
    if not stripped or stripped == "pass":
        return "// no-op"
    if stripped.startswith("return "):
        return f"return {stripped[len('return ') :].strip()};"
    if "=" in stripped and "==" not in stripped and not stripped.startswith("let "):
        name, value = stripped.split("=", 1)
        return f"let {name.strip()} = {value.strip()};"
    return stripped if stripped.endswith(";") else f"{stripped};"


def emit_rust(module: PrismModule) -> str:
    out: List[str] = ["// Generated by Code Prism.", ""]
    for fn in module.functions:
        out.append(_rust_signature(fn))
        for line in fn.body:
            out.append(f"    {_rust_body_line(line)}")
        out.append("}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def _c_type(type_name: str | None = None) -> str:
    if not type_name:
        return "double"
    normalised = type_name.strip().lower().replace(";", "")
    if normalised in {"int", "integer", "number", "float", "double", "f64", "i32", "i64"}:
        return "double"
    if normalised in {"bool", "boolean"}:
        return "bool"
    if normalised in {"none", "void", "()"}:
        return "void"
    return "double"


def _c_signature(fn: PrismFunction) -> str:
    ret = _c_type(fn.returns)
    arg_type = ret if ret != "void" else "double"
    args = ", ".join(f"{arg_type} {arg}" for arg in fn.args) or "void"
    return f"{ret} {fn.name}({args}) {{"


def _c_body_line(line: str, ret_type: str) -> str:
    stripped = line.strip()
    if not stripped or stripped == "pass":
        return "/* no-op */"
    if stripped.startswith("return "):
        return f"return {stripped[len('return ') :].strip()};"
    if "=" in stripped and "==" not in stripped:
        name, value = stripped.split("=", 1)
        decl_type = "double" if ret_type == "void" else ret_type
        return f"{decl_type} {name.strip()} = {value.strip()};"
    return stripped if stripped.endswith(";") else f"{stripped};"


def emit_c(module: PrismModule) -> str:
    out: List[str] = ["/* Generated by Code Prism. */", ""]
    for fn in module.functions:
        ret_type = _c_type(fn.returns)
        out.append(_c_signature(fn))
        for line in fn.body:
            out.append(f"    {_c_body_line(line, ret_type)}")
        if ret_type != "void" and not any(line.strip().startswith("return ") for line in fn.body):
            out.append("    return 0;")
        out.append("}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def _julia_body_line(line: str) -> str:
    stripped = line.strip()
    if not stripped or stripped == "pass":
        return "# no-op"
    if stripped.startswith("return "):
        return stripped
    return stripped


def emit_julia(module: PrismModule) -> str:
    out: List[str] = ["# Generated by Code Prism.", ""]
    for fn in module.functions:
        args = ", ".join(fn.args)
        out.append(f"function {fn.name}({args})")
        for line in fn.body:
            out.append(f"    {_julia_body_line(line)}")
        out.append("end")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def _return_expr(fn: PrismFunction) -> str:
    assignments: List[str] = []
    for line in fn.body:
        stripped = line.strip()
        if stripped.startswith("return "):
            expr = stripped[len("return ") :].strip()
            if assignments:
                return "let " + "; ".join(assignments) + f" in {expr}"
            return expr
        if "=" in stripped and "==" not in stripped:
            name, value = stripped.split("=", 1)
            assignments.append(f"{name.strip()} = {value.strip()}")
    return "()"


def emit_haskell(module: PrismModule) -> str:
    out: List[str] = ["-- Generated by Code Prism.", ""]
    for fn in module.functions:
        args = " ".join(fn.args)
        sep = " " if args else ""
        out.append(f"{fn.name}{sep}{args} = {_return_expr(fn)}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def emit_from_ir(module: PrismModule, target_language: str) -> str:
    lang = _lang(target_language)
    if lang == "python":
        return emit_python(module)
    if lang == "typescript":
        return emit_typescript(module)
    if lang == "go":
        return emit_go(module)
    if lang == "rust":
        return emit_rust(module)
    if lang == "c":
        return emit_c(module)
    if lang == "julia":
        return emit_julia(module)
    if lang == "haskell":
        return emit_haskell(module)
    raise ValueError(f"Unsupported target language: {target_language}")
