from __future__ import annotations

import ast
import json
from typing import List

from .models import PrismFunction, PrismModule

# --- Python safe-subset expression -> JS expression -------------------------------------------------
# Python-isms that differ from JS and silently break a passthrough emit:
#   a // b  -> in JS '//' starts a COMMENT (the whole tail vanishes)   [the bug this fixes]
#   a ** b  -> Math.pow                  and/or/not -> &&/||/!          True/False/None -> true/false/null
#   a < b < c (chained compare)          == -> ===                     len(x) -> (x).length
# Anything outside this subset raises, and the caller falls back to the RAW line (current behaviour),
# so this can never regress a case it already handled -- and the correctness gate catches any residue.
_JS_CALLS = {
    "abs": "Math.abs",
    "min": "Math.min",
    "max": "Math.max",
    "round": "Math.round",
    "int": "Math.trunc",
    "float": "Number",
}
_BIN = {ast.Add: "+", ast.Sub: "-", ast.Mult: "*", ast.Div: "/", ast.Mod: "%"}
_CMP = {ast.Lt: "<", ast.Gt: ">", ast.LtE: "<=", ast.GtE: ">=", ast.Eq: "===", ast.NotEq: "!=="}


def _js_expr(n: ast.AST) -> str:
    if isinstance(n, ast.Constant):
        v = n.value
        if v is True:
            return "true"
        if v is False:
            return "false"
        if v is None:
            return "null"
        return json.dumps(v) if isinstance(v, str) else repr(v)
    if isinstance(n, ast.Name):
        return n.id
    if isinstance(n, ast.BinOp):
        left, right = _js_expr(n.left), _js_expr(n.right)
        if isinstance(n.op, ast.FloorDiv):
            return f"Math.floor({left} / {right})"
        if isinstance(n.op, ast.Pow):
            return f"Math.pow({left}, {right})"
        sym = _BIN.get(type(n.op))
        if sym is None:
            raise ValueError("binop")
        return f"({left} {sym} {right})"
    if isinstance(n, ast.UnaryOp):
        operand = _js_expr(n.operand)
        if isinstance(n.op, ast.USub):
            return f"(-{operand})"
        if isinstance(n.op, ast.UAdd):
            return f"(+{operand})"
        if isinstance(n.op, ast.Not):
            return f"(!{operand})"
        raise ValueError("unaryop")
    if isinstance(n, ast.BoolOp):
        sym = "&&" if isinstance(n.op, ast.And) else "||"
        return "(" + f" {sym} ".join(_js_expr(v) for v in n.values) + ")"
    if isinstance(n, ast.Compare):
        parts, cur = [], _js_expr(n.left)
        for op, comp in zip(n.ops, n.comparators):
            rs = _js_expr(comp)
            sym = _CMP.get(type(op))
            if sym is None:
                raise ValueError("compare")
            parts.append(f"({cur} {sym} {rs})")
            cur = rs
        return "(" + " && ".join(parts) + ")"
    if isinstance(n, ast.IfExp):
        return f"({_js_expr(n.test)} ? {_js_expr(n.body)} : {_js_expr(n.orelse)})"
    if isinstance(n, ast.Call):
        if not isinstance(n.func, ast.Name) or n.keywords:
            raise ValueError("call")
        args = [_js_expr(a) for a in n.args]
        if n.func.id == "len" and len(args) == 1:
            return f"({args[0]}).length"
        target = _JS_CALLS.get(n.func.id, n.func.id)
        return f"{target}({', '.join(args)})"
    if isinstance(n, (ast.List, ast.Tuple)):
        return "[" + ", ".join(_js_expr(e) for e in n.elts) + "]"
    if isinstance(n, ast.Subscript):
        return f"{_js_expr(n.value)}[{_js_expr(n.slice)}]"
    raise ValueError("unsupported node " + type(n).__name__)


def _ts_expr(expr: str) -> str:
    """Translate a Python expression to JS; fall back to the raw text on anything unsupported."""
    try:
        return _js_expr(ast.parse(expr.strip(), mode="eval").body)
    except Exception:
        return expr


def _py_signature(fn: PrismFunction) -> str:
    args = ", ".join(fn.args)
    suffix = f" -> {fn.returns}" if fn.returns else ""
    return f"def {fn.name}({args}){suffix}:"


def emit_python(module: PrismModule) -> str:
    out: List[str] = ['"""Generated by Code Prism."""', ""]
    for fn in module.functions:
        out.append(_py_signature(fn))
        if fn.docstring:
            out.append(f'    """{fn.docstring}"""')
        for line in fn.body:
            out.append(f"    {line}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def _ts_signature(fn: PrismFunction) -> str:
    args = ", ".join(f"{arg}: any" for arg in fn.args)
    ret = _ts_type(fn.returns)
    return f"export function {fn.name}({args}): {ret} {{"


def _ts_type(type_name: str | None) -> str:
    if not type_name:
        return "any"
    normalised = type_name.strip().lower()
    if normalised in {"int", "float", "number"}:
        return "number"
    if normalised in {"str", "string"}:
        return "string"
    if normalised in {"bool", "boolean"}:
        return "boolean"
    if normalised in {"none", "void"}:
        return "void"
    return type_name


def _ts_body_line(line: str) -> str:
    stripped = line.strip()
    if not stripped or stripped == "pass":
        return "// no-op"
    if stripped.startswith("return "):
        return f"return {_ts_expr(stripped[len('return '):])};"
    if "=" in stripped and "==" not in stripped and not stripped.startswith(("const ", "let ", "var ")):
        name, value = stripped.split("=", 1)
        return f"const {name.strip()} = {_ts_expr(value.strip())};"
    return stripped if stripped.endswith(";") else f"{stripped};"


def emit_typescript(module: PrismModule) -> str:
    out: List[str] = ["// Generated by Code Prism.", ""]
    for fn in module.functions:
        out.append(_ts_signature(fn))
        if fn.docstring:
            out.append(f"  // {fn.docstring}")
        if fn.body:
            for line in fn.body:
                out.append(f"  {_ts_body_line(line)}")
        else:
            out.append("  // no-op")
        out.append("}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def _go_type(fn: PrismFunction) -> str:
    if fn.returns:
        normalised = fn.returns.strip().lower()
        if normalised in {"int", "float", "number"}:
            return "float64"
        if normalised in {"str", "string"}:
            return "string"
        if normalised in {"bool", "boolean"}:
            return "bool"
        if normalised in {"none", "void"}:
            return ""
    arithmetic_markers = (" + ", " - ", " * ", " / ")
    if any(line.strip().startswith("return ") and any(op in line for op in arithmetic_markers) for line in fn.body):
        return "float64"
    return "interface{}"


def _go_signature(fn: PrismFunction) -> str:
    ret = _go_type(fn)
    arg_type = ret or "interface{}"
    args = ", ".join(f"{arg} {arg_type}" for arg in fn.args)
    suffix = f" {ret}" if ret else ""
    return f"func {fn.name.title()}({args}){suffix} {{"


def _go_zero_value(type_name: str) -> str:
    if type_name == "float64":
        return "0"
    if type_name == "string":
        return '""'
    if type_name == "bool":
        return "false"
    return "nil"


def _go_body_line(line: str) -> str:
    stripped = line.strip()
    if not stripped or stripped == "pass":
        return "// no-op"
    if stripped.startswith("return "):
        return stripped
    for keyword in ("const ", "let ", "var "):
        if stripped.startswith(keyword):
            stripped = stripped[len(keyword) :].strip()
            break
    if "=" in stripped and "==" not in stripped and ":=" not in stripped:
        name, value = stripped.split("=", 1)
        return f"{name.strip()} := {value.strip()}"
    if stripped.startswith("//"):
        return stripped
    return f"// unsupported safe-subset statement: {stripped}"


def emit_go(module: PrismModule) -> str:
    out: List[str] = [
        "// Generated by Code Prism.",
        "package prism",
        "",
    ]
    for fn in module.functions:
        ret_type = _go_type(fn)
        out.append(_go_signature(fn))
        if fn.docstring:
            out.append(f"    // {fn.docstring}")
        emitted_return = False
        for line in fn.body:
            go_line = _go_body_line(line)
            if go_line.startswith("return "):
                emitted_return = True
            out.append(f"    {go_line}")
        if not emitted_return and ret_type:
            out.append(f"    return {_go_zero_value(ret_type)}")
        out.append("}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def emit_from_ir(module: PrismModule, target_language: str) -> str:
    lang = target_language.lower()
    if lang == "python":
        return emit_python(module)
    if lang in {"typescript", "ts"}:
        return emit_typescript(module)
    if lang == "go":
        return emit_go(module)
    raise ValueError(f"Unsupported target language: {target_language}")
