#!/usr/bin/env python3
"""Build a SELF-CONTAINED comprehensive Kaggle kernel from the live SCBE modules.

Generates one stdlib+numpy-only file that exercises the whole Rubik's-Cube coding
system on Kaggle free compute:

  B1  emit throughput        one CA-opcode core -> all 18 language faces
  B2  roundabout parity      defined "undefined zones" (div0, sqrt-neg -> 0.0)
  B3  18-language validity    every face emits valid source for random programs
  B4  geometric routing       tangentialism: Finsler routing vs round-robin
  B5  scaling sweep           emit throughput stays linear as the batch grows

Fidelity: the 18 dialects + roundabout logic are serialized from the live
python/scbe/polyglot.py registry; the router is sliced verbatim from
python/scbe/geometric_router.py. No repo import survives into the kernel.
"""

from __future__ import annotations

import base64
import json
import re
from dataclasses import asdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
import sys

sys.path.insert(0, str(ROOT))

from python.scbe import polyglot as P  # noqa: E402


def dump_data() -> str:
    """Serialize the live 18-dialect registry + op tables to a base64 JSON blob."""
    dialects = {name: asdict(d) for name, d in P.REGISTRY.items()}
    data = {
        "dialects": dialects,
        "ops": {
            "BINOPS": P.BINOPS,
            "CMPS": P.CMPS,
            "FUNC2": sorted(P.FUNC2),
            "FUNC1": sorted(P.FUNC1),
        },
    }
    raw = json.dumps(data, separators=(",", ":")).encode("utf-8")
    return base64.b64encode(raw).decode("ascii")


def slice_router() -> str:
    """Lift the numpy router (TONGUES .. round_robin) verbatim, drop demo + __future__."""
    src = (ROOT / "python" / "scbe" / "geometric_router.py").read_text(encoding="utf-8")
    start = src.index("TONGUES: Tuple")
    end = src.index("# --- demo")
    body = src[start:end].rstrip()
    return (
        "import numpy as np\nfrom dataclasses import dataclass, field\n"
        "from typing import Dict, List, Sequence, Tuple\n\n" + body
    )


KERNEL = r'''#!/usr/bin/env python3
"""SELF-CONTAINED Kaggle kernel -- Rubik's-Cube Coding System, full-system benchmark.

ONE CA-opcode core -> all 18 language faces, plus the geometric (tangentialism)
fleet router. No repo clone, no pip install: the 18 dialects + roundabout logic
are inlined (base64) and the router is inlined verbatim. stdlib + numpy only.
Auto-generated by scripts/kaggle_auto/build_comprehensive_kernel.py -- do not edit.
"""
import base64
import json
import math
import multiprocessing
import os
import platform
import random
import shutil
import subprocess
import tempfile
import time

_DATA = json.loads(base64.b64decode("__DATA_B64__").decode("utf-8"))
DIALECTS = _DATA["dialects"]
OPS = _DATA["ops"]
BINOPS, CMPS = OPS["BINOPS"], OPS["CMPS"]
FUNC2, FUNC1 = set(OPS["FUNC2"]), set(OPS["FUNC1"])
LANGS = sorted(DIALECTS)


# ---- emitter (mirrors python/scbe/polyglot.py, incl. roundabout safe mode) ----
def _sub(tmpl, **kw):
    for k, v in kw.items():
        tmpl = tmpl.replace("{" + k + "}", str(v))
    return tmpl


def _ternary(d):
    """General select(cond,t,f) derived from the dialect's own comparison template."""
    t = d["cmp_tmpl"].replace("1.0", "{t}").replace("0.0", "{f}")
    if "{t}" not in t or "{f}" not in t:
        t = "({cond} ? {t} : {f})"
    return t


def render(name, d, safe=False):
    """Return (push-expression over temp vars a/b, is_binary). Roundabouts when safe."""
    if name in BINOPS:
        op = d["binop_over"].get(name, BINOPS[name])
        expr = "a " + op + " b"
        if safe and name == "div":
            expr = _sub(_ternary(d), cond="b == 0.0", t="0.0", f="a / b")
        return expr, True
    if name in CMPS:
        return _sub(d["cmp_tmpl"], cond="a " + CMPS[name] + " b"), True
    if name in FUNC2:
        expr = _sub(d["func2"][name], a="a", b="b")
        if safe and name == "mod":
            expr = _sub(_ternary(d), cond="b == 0.0", t="0.0", f=expr)
        return expr, True
    expr = _sub(d["func1"][name], a="a")
    if safe and name == "sqrt":
        expr = _sub(_ternary(d), cond="a < 0.0", t="0.0", f=expr)
    return expr, False


def emit(names, lang, fn="tongue_fn", args=("a", "b", "c"), runnable=False, safe=False):
    d = DIALECTS[lang]
    ind = d["indent"]
    L = list(d["prelude"])
    L.append(_sub(d["fn_open"], fn=fn, params=", ".join(args)))
    L.append(ind + _sub(d["stack_init"], init=", ".join(args)))
    for n in names:
        expr, is_bin = render(n, d, safe=safe)
        pop = d["pop2"] if is_bin else d["pop1"]
        L.append(ind + pop + _sub(d["push"], expr=expr) + "  " + d["comment"] + " " + n)
    L.append(ind + d["ret"])
    L.extend(d["fn_close"])
    if runnable and d["main_tmpl"]:
        L.append("")
        L.extend(_sub(m, fn=fn) for m in d["main_tmpl"])
    return "\n".join(L) + "\n"


_BIN = sorted(set(BINOPS) | set(CMPS) | FUNC2)
_UN = sorted(FUNC1)


def rand_prog(length, rng):
    depth, ops = 3, []
    for _ in range(length):
        if depth >= 2 and rng.random() < 0.6:
            ops.append(rng.choice(_BIN))
            depth -= 1
        else:
            ops.append(rng.choice(_UN))
        if depth < 1:
            depth = 1
    return ops


def run_python(names, safe):
    ns = {}
    exec(compile(emit(names, "python", safe=safe), "p.py", "exec"), ns)  # noqa: S102
    return ns["tongue_fn"](2.0, 3.0, 4.0)


# ============================ INLINED GEOMETRIC ROUTER =========================
__ROUTER__
# ==============================================================================


# ---- B1: emit throughput -----------------------------------------------------
def b1_emit(n, length, seed=7):
    rng = random.Random(seed)
    progs = [rand_prog(length, rng) for _ in range(n)]
    t0 = time.perf_counter()
    files = lines = chars = 0
    for p in progs:
        for lang in LANGS:
            s = emit(p, lang)
            files += 1
            lines += s.count("\n")          # output already ends in \n -> true line count
            chars += len(s)
    dt = time.perf_counter() - t0
    return dict(languages=len(LANGS), programs=n, ops=length, files=files, seconds=dt,
                programs_per_s=n / dt, files_per_s=files / dt,
                kloc_per_s=lines / 1000 / dt, mchars_per_s=chars / 1e6 / dt)


# ---- B2: roundabout parity (defined undefined-zones) -------------------------
def b2_roundabouts():
    cases = [("div0", ["eq", "div"], "ZeroDivisionError"),
             ("sqrt_neg", ["sub", "sqrt"], "ValueError")]
    out = {}
    for tag, prog, want_exc in cases:
        raw_exc = None
        try:
            run_python(prog, safe=False)
        except BaseException as e:           # pin the exact type rather than swallow all
            raw_exc = type(e).__name__
        safe_val = run_python(prog, safe=True)
        out[tag] = dict(raw_exc=raw_exc, raw_raises_expected=(raw_exc == want_exc),
                        safe_value=safe_val, safe_defined=(safe_val == 0.0))
    # safe-mode emits for every language without error, and differs from raw on the op
    emit_ok = 0
    for lang in LANGS:
        try:
            safe_src = emit(["add", "div", "sqrt", "mod"], lang, safe=True)
            raw_src = emit(["add", "div", "sqrt", "mod"], lang, safe=False)
            if safe_src and safe_src != raw_src:
                emit_ok += 1
        except Exception:
            pass
    out["safe_emit_langs"] = emit_ok
    out["total_langs"] = len(LANGS)
    return out


# ---- B3a: emitter shape self-check (NOT a compile proof) ----------------------
def b3_shape(n, length, seed=11):
    """An emitter invariant, honestly labelled: every emit is well-formed (boilerplate
    present AND delimiters balanced). This is NOT evidence the code compiles -- that is
    B3b below. Delimiter balance is the one part that could actually fail on a bad
    template, so it is a real (if weak) structural signal beyond the tautological parts."""
    rng = random.Random(seed)
    progs = [rand_prog(length, rng) for _ in range(n)]
    total = ok = balanced = 0
    for p in progs:
        for lang in LANGS:
            for safe in (False, True):
                s = emit(p, lang, runnable=True, safe=safe)
                total += 1
                d = DIALECTS[lang]
                shape_ok = s.endswith("\n") and "tongue_fn" in s and (
                    not d["fn_close"] or d["fn_close"][-1] in s)
                bal = (s.count("(") == s.count(")") and s.count("{") == s.count("}")
                       and s.count("[") == s.count("]"))
                ok += shape_ok
                balanced += bal
    return dict(programs=n, langs=len(LANGS), checks=total, shape_ok=ok,
                balanced=balanced, shape_pct=100.0 * ok / total,
                balanced_pct=100.0 * balanced / total)


# ---- B3b: REAL cross-language compile + run numeric parity --------------------
# The honest validity test: actually build & run each language whose toolchain is
# present on this node, and check it computes the SAME number python does. Languages
# with no toolchain here are reported as skipped -- never silently counted as passing.
_TOOLCHAINS = {
    "c":          dict(ext="c",   build=["gcc", "-O2", "-o", "{exe}", "{src}", "-lm"], run=["{exe}"]),
    "cpp":        dict(ext="cpp", build=["g++", "-O2", "-o", "{exe}", "{src}"],        run=["{exe}"]),
    "rust":       dict(ext="rs",  build=["rustc", "-O", "-o", "{exe}", "{src}"],       run=["{exe}"]),
    "javascript": dict(ext="js",  run=["node", "{src}"]),
    "typescript": dict(ext="ts",  run=["ts-node", "{src}"]),
    "go":         dict(ext="go",  run=["go", "run", "{src}"]),
    "ruby":       dict(ext="rb",  run=["ruby", "{src}"]),
    "php":        dict(ext="php",  run=["php", "{src}"]),
    "lua":        dict(ext="lua", run=["lua", "{src}"]),
    "julia":      dict(ext="jl",  run=["julia", "{src}"]),
    "java":       dict(ext="java", fname="Main.java", build=["javac", "{src}"], run=["java", "-cp", "{dir}", "Main"]),
    "kotlin":     dict(ext="kt",  build=["kotlinc", "{src}", "-include-runtime", "-d", "{exe}.jar"],
                       run=["java", "-jar", "{exe}.jar"]),
    "scala":      dict(ext="scala", run=["scala", "{src}"]),
    "swift":      dict(ext="swift", run=["swift", "{src}"]),
    "haskell":    dict(ext="hs",  run=["runghc", "{src}"]),
    "csharp":     dict(ext="cs",  run=["dotnet", "script", "{src}"]),
    "zig":        dict(ext="zig", run=["zig", "run", "{src}"]),
}


def _toolchain_present(spec):
    tool = (spec.get("build") or spec["run"])[0]
    return shutil.which(tool) is not None


def b3_compile(nprog=4, length=8, seed=17, timeout=25):
    rng = random.Random(seed)
    progs, refs = [], []
    while len(progs) < nprog:                 # only well-defined programs (clean ref)
        p = rand_prog(length, rng)
        try:
            refs.append(float(run_python(p, safe=False)))
            progs.append(p)
        except Exception:
            continue
    per_lang = {}
    tmp = tempfile.mkdtemp(prefix="cube_")
    for lang in LANGS:
        spec = _TOOLCHAINS.get(lang)
        # python: always available, executed in-process
        if lang == "python":
            okc = sum(1 for p, r in zip(progs, refs)
                      if abs(float(run_python(p, safe=False)) - r) < 1e-6)
            per_lang["python"] = dict(present=True, ok=okc, n=len(progs))
            continue
        if not spec or not _toolchain_present(spec):
            per_lang[lang] = dict(present=False, ok=0, n=len(progs))
            continue
        okc = 0
        for i, (p, r) in enumerate(zip(progs, refs)):
            d = os.path.join(tmp, "%s_%d" % (lang, i))
            os.makedirs(d, exist_ok=True)
            src = os.path.join(d, spec.get("fname", "prog.%s" % spec["ext"]))
            exe = os.path.join(d, "prog")
            with open(src, "w", encoding="utf-8") as fh:
                fh.write(emit(p, lang, runnable=True, safe=False))
            sub = lambda c: [x.replace("{src}", src).replace("{exe}", exe).replace("{dir}", d) for x in c]
            try:
                if "build" in spec:
                    b = subprocess.run(sub(spec["build"]), capture_output=True, timeout=timeout, cwd=d)
                    if b.returncode != 0:
                        continue
                run = subprocess.run(sub(spec["run"]), capture_output=True, timeout=timeout, cwd=d, text=True)
                if run.returncode != 0 or not run.stdout.strip():
                    continue
                got = float(run.stdout.strip().split()[-1])
                if abs(got - r) < 1e-6:
                    okc += 1
            except Exception:
                continue
        per_lang[lang] = dict(present=True, ok=okc, n=len(progs))
    shutil.rmtree(tmp, ignore_errors=True)
    present = [l for l in LANGS if per_lang[l]["present"]]
    fully_ok = [l for l in present if per_lang[l]["ok"] == len(progs)]
    return dict(programs=len(progs), per_lang=per_lang, present=present,
                present_count=len(present), fully_parity=fully_ok,
                fully_parity_count=len(fully_ok))


def b3_exec_parity(length=12):
    """Python safe==raw where the math is already defined (roundabouts don't change defined results)."""
    parity = ok = 0
    rng = random.Random(13)
    for _ in range(200):
        p = rand_prog(length, rng)
        try:
            raw = run_python(p, safe=False)
        except Exception:
            continue
        parity += 1
        if run_python(p, safe=True) == raw:
            ok += 1
    return dict(checked=parity, ok=ok)


# ---- B4: geometric routing (tangentialism) vs round-robin --------------------
def b4_routing(sizes=(30, 120, 480), seed=7):
    # agents run in PARALLEL, so the metric that reflects wall-time is makespan =
    # the busiest agent's summed cost, not the fleet-wide total. Geometry balances
    # load AND respects tongue affinity, so it wins on makespan even at saturation.
    fleet = [Agent("%s-agent" % t, {t: 1.0}) for t in TONGUES]
    runs = []
    for ntask in sizes:
        rng = np.random.default_rng(seed)
        tasks = []
        for i in range(ntask):
            prof = {t: float(rng.random()) for t in TONGUES}
            if i % 3 == 0:
                dom = TONGUES[i % 6]
                prof = {t: (1.0 if t == dom else 0.1 * float(rng.random())) for t in TONGUES}
            tasks.append(Task("task%04d" % i, prof))
        t0 = time.perf_counter()
        routes = route_fleet(fleet, tasks, pressure=0.6, tour=False)
        dt = time.perf_counter() - t0
        geo_total = sum(r.total_cost for r in routes)
        geo_make = max((r.total_cost for r in routes), default=0.0)
        # round-robin per-agent makespan: chunk by index, sum each agent's distances
        rr_loads = [0.0] * len(fleet)
        for i, t in enumerate(tasks):
            a = fleet[i % len(fleet)]
            rr_loads[i % len(fleet)] += finsler_distance(a.pos, t.profile, a.tongue)
        rr_total, rr_make = sum(rr_loads), max(rr_loads)
        runs.append(dict(tasks=ntask, geo_total=geo_total, rr_total=rr_total,
                         geo_makespan=geo_make, rr_makespan=rr_make,
                         makespan_cheaper_pct=100.0 * (1 - geo_make / rr_make) if rr_make else 0.0,
                         total_cheaper_pct=100.0 * (1 - geo_total / rr_total) if rr_total else 0.0,
                         route_seconds=dt))
    return runs


# ---- B5: scaling sweep -------------------------------------------------------
def b5_scaling(counts=(1000, 4000, 16000), length=12):
    out = []
    for n in counts:
        r = b1_emit(n, length, seed=3)
        out.append(dict(programs=n, programs_per_s=r["programs_per_s"],
                        files_per_s=r["files_per_s"], kloc_per_s=r["kloc_per_s"]))
    return out


def main():
    print("=" * 60)
    print("RUBIK'S-CUBE CODING SYSTEM  -  KAGGLE FULL-SYSTEM BENCHMARK")
    print("=" * 60)
    print("node :", platform.platform())
    print("cores:", multiprocessing.cpu_count(), " python:", platform.python_version())
    print("faces:", len(LANGS), "languages ->", ", ".join(LANGS))
    results = {"node": platform.platform(), "cores": multiprocessing.cpu_count(),
               "python": platform.python_version(), "languages": LANGS}

    print("\n[B1] EMIT THROUGHPUT  (one core -> all 18 faces)")
    results["b1"] = []
    for n, L in [(5000, 12), (20000, 16)]:
        r = b1_emit(n, L)
        results["b1"].append(r)
        print("  %6d progs x %2d ops -> %7d files  |  %9.0f progs/s  %9.0f files/s  "
              "%7.1f KLOC/s  %5.2f Mchar/s  (%.2fs)" % (
                  r["programs"], r["ops"], r["files"], r["programs_per_s"],
                  r["files_per_s"], r["kloc_per_s"], r["mchars_per_s"], r["seconds"]))

    print("\n[B2] ROUNDABOUTS  (defined 'undefined zones' -- div0 / sqrt-neg)")
    rb = b2_roundabouts()
    results["b2"] = rb
    for tag in ("div0", "sqrt_neg"):
        c = rb[tag]
        print("  %-9s raw python raises %-18s  ->  safe roundabout value: %s (defined=%s)" % (
            tag, c["raw_exc"], c["safe_value"], c["safe_defined"]))
    print("  safe-mode emits cleanly for %d/%d languages" % (rb["safe_emit_langs"], rb["total_langs"]))

    print("\n[B3a] EMITTER SHAPE SELF-CHECK  (invariant, NOT a compile proof)")
    sh = b3_shape(300, 12)
    results["b3_shape"] = sh
    print("  %d emits  ->  %.1f%% well-formed boilerplate, %.1f%% balanced ()/{}/[]" % (
        sh["checks"], sh["shape_pct"], sh["balanced_pct"]))

    print("\n[B3b] REAL CROSS-LANGUAGE COMPILE + RUN PARITY  (toolchains present on THIS node)")
    cp = b3_compile()
    results["b3_compile"] = cp
    print("  %d programs compiled+run per available language; same number as python = parity" % cp["programs"])
    print("  toolchains present: %d/18  ->  %s" % (cp["present_count"], ", ".join(cp["present"])))
    print("  full numeric parity: %d/%d present langs  ->  %s" % (
        cp["fully_parity_count"], cp["present_count"], ", ".join(cp["fully_parity"])))
    miss = [l for l in cp["present"] if l not in cp["fully_parity"]]
    if miss:
        print("  present but NOT full-parity (investigate): %s" % ", ".join(miss))
    ep = b3_exec_parity()
    results["b3_exec_parity"] = ep
    print("  python safe==raw where defined: %d/%d" % (ep["ok"], ep["checked"]))

    print("\n[B4] GEOMETRIC ROUTING  (tangentialism: Finsler vs round-robin)")
    print("     makespan = busiest agent's load (parallel wall-time); total = fleet-wide work.")
    print("     geometry trades a little total work for lower makespan (load balance);")
    print("     the makespan win holds at saturation, the total win erodes -- both shown.")
    rt = b4_routing()
    results["b4"] = rt
    for r in rt:
        print("  %4d tasks  makespan geo %7.2f vs rr %7.2f (%+4.0f%%)   "
              "total geo %8.2f vs rr %8.2f (%+4.0f%%)   route %.3fs (assignment only)" % (
                  r["tasks"], r["geo_makespan"], r["rr_makespan"], r["makespan_cheaper_pct"],
                  r["geo_total"], r["rr_total"], r["total_cheaper_pct"], r["route_seconds"]))

    print("\n[B5] SCALING SWEEP  (emit throughput stays linear)")
    sc = b5_scaling()
    results["b5"] = sc
    for r in sc:
        print("  %6d programs  ->  %9.0f progs/s   %9.0f files/s   %7.1f KLOC/s" % (
            r["programs"], r["programs_per_s"], r["files_per_s"], r["kloc_per_s"]))

    print("\n" + "=" * 60)
    print("=== MACHINE JSON ===")
    print(json.dumps(results, default=float))
    print("DONE")


if __name__ == "__main__":
    main()
'''


def main() -> None:
    out_dir = ROOT / "scripts" / "kaggle_auto" / "rubix_bench_comprehensive"
    out_dir.mkdir(parents=True, exist_ok=True)
    kernel = KERNEL.replace("__DATA_B64__", dump_data()).replace("__ROUTER__", slice_router())
    kpath = out_dir / "comprehensive_selfcontained.py"
    kpath.write_text(kernel, encoding="utf-8")

    meta = {
        "id": "issacizrealdavis/rubix-cube-full-system-benchmark",
        "title": "Rubik's Cube Coding System - Full-System Benchmark",
        "code_file": "comprehensive_selfcontained.py",
        "language": "python",
        "kernel_type": "script",
        "is_private": "true",
        "enable_gpu": "false",
        "enable_internet": "false",
        "dataset_sources": [],
        "competition_sources": [],
        "kernel_sources": [],
    }
    (out_dir / "kernel-metadata.json").write_text(json.dumps(meta, indent=1), encoding="utf-8")
    size = kpath.stat().st_size
    n_router = slice_router().count("\n")
    print("wrote %s  (%d bytes, %d languages, router %d lines)" % (kpath, size, len(P.REGISTRY), n_router))
    print("wrote %s" % (out_dir / "kernel-metadata.json"))


if __name__ == "__main__":
    main()
