"""Export only the six public byte vocabularies into a deterministic Lean fixture."""

import argparse
import hashlib
import importlib.util
import json
from pathlib import Path
import sys


def render(repo):
    source = repo / "src/crypto/sacred_tongues.py"
    spec = importlib.util.spec_from_file_location("_vocabulary_export", source)
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    codec = module.SacredTongueTokenizer()
    codes = ["ko", "av", "ru", "ca", "um", "dr"]
    if set(codes) != set(module.TONGUES):
        raise ValueError("Unexpected tongue registry")
    lines = [
        "import Mathlib.Data.List.Basic",
        "",
        "namespace SCBE.Vocabulary",
        "",
        "/- Generated by export_vocabulary.py; public table data only.",
        "   Source SHA-256 (UTF-8, normalized LF): "
        + hashlib.sha256(source.read_text(encoding="utf-8").encode("utf-8")).hexdigest(),
        "   Order: ko, av, ru, ca, um, dr. -/",
        "",
        "def tables : List (List String) := [",
    ]
    for i, code in enumerate(codes):
        row = codec.encode_bytes(code, bytes(range(256)))
        lines.append(
            "  [" + ", ".join(json.dumps(token, ensure_ascii=False) for token in row) + "]" + ("," if i < 5 else "")
        )
    lines.extend(
        [
            "]",
            "",
            "set_option maxRecDepth 10000",
            "set_option maxHeartbeats 4000000",
            "",
            "theorem exactly_six_tables : tables.length = 6 := by decide",
            "",
            "theorem each_table_has_256_symbols : ∀ row ∈ tables, row.length = 256 := by decide",
            "",
            "/- Concrete uniqueness and decoder agreement are checked by audit_implementation.py.",
            "   Codecs.lean proves the sequence laws assuming an equivalence for each vocabulary. -/",
            "",
            "end SCBE.Vocabulary",
            "",
        ]
    )
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = Path(__file__).parent / "SCBE/Vocabulary.lean"
    text = render(args.repo)
    if args.check:
        if target.read_text(encoding="utf-8") != text:
            raise SystemExit("Vocabulary fixture differs from the named source; regenerate and reprove")
        print("Vocabulary fixture matches the named source")
    else:
        target.write_text(text, encoding="utf-8", newline="\n")
        print(target)
