#!/usr/bin/env node
'use strict';

// Regenerates api/agent/router.js and api/polly/router.js, and rewrites vercel.json
// route destinations to point at them.
//
// WHY ROUTERS EXIST: the Hobby plan caps a deployment at 12 serverless functions.
// The old `builds` globs turned every handler file into its own function — 58 of them
// (49 agent + 8 polly + 1 billing) — so EVERY deploy failed at the plan gate, no matter
// what the commit changed. Consolidating each lane behind one dispatcher function brings
// the count to 3: agent router, polly router, and the Stripe webhook.
//
// The webhook stays its own function deliberately: it exports
// `config = { api: { bodyParser: false } }` because signature verification needs the raw
// request bytes. A shared router has one config for every handler behind it, so folding
// the webhook in would either break its signature check (parsed body) or strip req.body
// from every other handler (parser off globally).
//
// WHY THE MAP IS LITERAL REQUIRES: Vercel's bundler (ncc) traces STATIC require calls to
// decide what to pack into the lambda. `require(someVariable)` traces to nothing — the
// router would deploy fine and then 500 on every request because no handler files shipped.
// Generating the file keeps the literal map in sync with the directory without hand-editing
// 50 lines; scripts/vercel/verify-router.cjs checks the sync in CI terms (run it locally).
//
// Handler contract, verified before generation: `module.exports = [async] function (req, res)`.
// Files that don't match (shared libraries like _static_file.js and commerce.js) are
// skipped — under the old globs those deployed as functions too, and invoking one crashed
// at runtime. Not mapping them is the honest 404.

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');
const HANDLER_EXPORT = /^module\.exports\s*=\s*(async\s+)?function/m;

function laneHandlers(lane) {
  const dir = path.join(ROOT, 'api', lane);
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith('.js') && !f.startsWith('_') && f !== 'router.js')
    .filter((f) => HANDLER_EXPORT.test(fs.readFileSync(path.join(dir, f), 'utf8')))
    .map((f) => f.slice(0, -3))
    .sort();
}

function routerSource(lane, names) {
  // prettier unquotes identifier-safe keys; emit its style so `generate` output always
  // passes `prettier --check` without a second pass
  const key = (n) => (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(n) ? n : `'${n}'`);
  const entries = names.map((n) => `  ${key(n)}: () => require('./${n}.js'),`).join('\n');
  return `'use strict';

// GENERATED by scripts/vercel/generate-router.cjs — edit that, not this.
//
// One Vercel function for the whole /api/${lane} lane. The Hobby plan allows 12
// serverless functions per deployment; building every handler as its own function
// put this repo at 58 and made every deploy fail at the plan gate. vercel.json
// routes now land here with ?fn=<name> and the map below dispatches in-process.
//
// The map is literal require calls ON PURPOSE: the bundler traces static requires
// to decide which files ship inside the lambda. A require(variable) would deploy a
// router with nothing behind it. Lazy thunks keep one broken handler from taking
// down the rest of the lane at require time.

const HANDLERS = {
${entries}
};

module.exports = async function router(req, res) {
  const candidates = [];
  const queryValue = req.query && req.query.fn;
  if (Array.isArray(queryValue)) {
    candidates.push(...queryValue);
  } else if (typeof queryValue === 'string') {
    candidates.push(queryValue);
  }
  try {
    candidates.push(...new URL(req.url, 'http://router.internal').searchParams.getAll('fn'));
  } catch (_err) {
    // Vercel normally supplies req.query; malformed local mock URLs may not.
  }
  const fn =
    candidates.find(
      (candidate) =>
        typeof candidate === 'string' &&
        Object.prototype.hasOwnProperty.call(HANDLERS, candidate)
    ) || '';
  if (!Object.prototype.hasOwnProperty.call(HANDLERS, fn)) {
    // Everything in the map was already directly routable before consolidation, so the
    // router adds no new surface; anything else was a 404 then and stays one now.
    res.statusCode = 404;
    res.setHeader('content-type', 'application/json; charset=utf-8');
    res.end(JSON.stringify({ error: 'not_found', lane: '${lane}' }));
    return;
  }
  const handler = HANDLERS[fn]();
  if (typeof handler !== 'function') {
    throw new TypeError(\`api/${lane}/\${fn}.js does not export a request handler\`);
  }
  return handler(req, res);
};
`;
}

function rewriteDest(dest) {
  // "/api/agent/launch.js"            -> "/api/agent/router.js?fn=launch"
  // "/api/agent/static.js?path=$1"    -> "/api/agent/router.js?fn=static&path=$1"
  // "/api/agent/$1.js"  (catch-all)   -> "/api/agent/router.js?fn=$1"
  const m = dest.match(/^\/api\/(agent|polly)\/([^?]+)\.js(?:\?(.*))?$/);
  if (!m) return dest; // billing + anything already rewritten stay as-is
  const [, lane, name, query] = m;
  if (name === 'router') return dest;
  return `/api/${lane}/router.js?fn=${name}${query ? `&${query}` : ''}`;
}

function main() {
  const lanes = { agent: laneHandlers('agent'), polly: laneHandlers('polly') };
  for (const [lane, names] of Object.entries(lanes)) {
    fs.writeFileSync(path.join(ROOT, 'api', lane, 'router.js'), routerSource(lane, names));
    console.log(`api/${lane}/router.js  <- ${names.length} handlers`);
  }

  const vercelPath = path.join(ROOT, 'vercel.json');
  const cfg = JSON.parse(fs.readFileSync(vercelPath, 'utf8'));
  cfg.builds = [
    { src: 'api/agent/router.js', use: '@vercel/node' },
    { src: 'api/polly/router.js', use: '@vercel/node' },
    // raw-body function; see header comment for why it cannot share a router
    { src: 'api/billing/stripe_webhook.js', use: '@vercel/node' },
  ];
  cfg.routes = cfg.routes.map((r) => (r.dest ? { ...r, dest: rewriteDest(r.dest) } : r));
  fs.writeFileSync(vercelPath, JSON.stringify(cfg, null, 2) + '\n');
  console.log(
    `vercel.json          <- ${cfg.builds.length} functions, ${cfg.routes.length} routes`
  );
}

main();
