"""
@file doc_handler.py
@module browser/extensions/doc_handler
@layer Layer 13, Layer 14
@component DocHandler — Document creation from browser-extracted content

Creates documents (DOCX, Markdown, plain text) from headless browser extractions
and pushes them to cloud targets (GitHub, local filesystem).

Usage:
    handler = DocHandler(github_token="ghp_...", github_repo="owner/repo")

    # Extract page content and create a document
    doc = handler.extract_to_doc(title="Research Report", content=page_text, links=links)

    # Save locally as DOCX
    handler.save_docx(doc, "output/report.docx")

    # Push to GitHub as markdown
    result = handler.push_to_github(doc, path="docs/report.md", branch="main")

    # Or save as markdown locally
    handler.save_markdown(doc, "output/report.md")
"""

from __future__ import annotations

import hashlib
import json
import logging
import os
import time
import urllib.error
import urllib.request
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger("aetherbrowse-doc-handler")


@dataclass
class ExtractedDocument:
    """A document assembled from browser-extracted content."""

    title: str
    content: str
    source_urls: List[str] = field(default_factory=list)
    links: List[str] = field(default_factory=list)
    screenshots: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    doc_id: str = ""

    def __post_init__(self):
        if not self.doc_id:
            seed = f"{self.title}:{self.created_at}:{len(self.content)}"
            self.doc_id = hashlib.sha256(seed.encode()).hexdigest()[:16]

    def to_markdown(self) -> str:
        """Convert document to GitHub-flavored markdown."""
        lines = [f"# {self.title}", ""]

        if self.metadata:
            lines.append("## Metadata")
            lines.append("")
            lines.append(f"- **Generated**: {self.created_at}")
            lines.append(f"- **Doc ID**: `{self.doc_id}`")
            if self.source_urls:
                lines.append(f"- **Sources**: {len(self.source_urls)}")
            for k, v in self.metadata.items():
                if k not in ("generated", "doc_id"):
                    lines.append(f"- **{k}**: {v}")
            lines.append("")

        lines.append("## Content")
        lines.append("")
        lines.append(self.content)
        lines.append("")

        if self.source_urls:
            lines.append("## Sources")
            lines.append("")
            for i, url in enumerate(self.source_urls, 1):
                lines.append(f"{i}. {url}")
            lines.append("")

        if self.links:
            lines.append("## Related Links")
            lines.append("")
            for link in self.links[:50]:
                lines.append(f"- {link}")
            lines.append("")

        lines.append("---")
        lines.append(f"*Generated by SCBE AetherBrowse DocHandler at {self.created_at}*")
        return "\n".join(lines)

    def to_plain_text(self) -> str:
        """Convert document to plain text."""
        lines = [self.title, "=" * len(self.title), ""]
        lines.append(self.content)
        lines.append("")
        if self.source_urls:
            lines.append("Sources:")
            for url in self.source_urls:
                lines.append(f"  - {url}")
        return "\n".join(lines)


class DocHandler:
    """
    Creates documents from browser-extracted content and pushes to cloud targets.

    Supports:
    - Local save: DOCX, Markdown, plain text, JSON
    - GitHub: Create/update files via REST API
    - Batch processing: Multiple pages → single document
    """

    def __init__(
        self,
        github_token: Optional[str] = None,
        github_repo: Optional[str] = None,
        output_dir: str = "artifacts/documents",
    ):
        self.github_token = github_token or os.getenv("GITHUB_TOKEN", "")
        self.github_repo = github_repo or os.getenv("GITHUB_REPO", "")
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    # ── Document Creation ──────────────────────────────────────────────

    def extract_to_doc(
        self,
        title: str,
        content: str,
        source_urls: Optional[List[str]] = None,
        links: Optional[List[str]] = None,
        screenshots: Optional[List[str]] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> ExtractedDocument:
        """Create a document from extracted browser content."""
        return ExtractedDocument(
            title=title,
            content=content,
            source_urls=source_urls or [],
            links=links or [],
            screenshots=screenshots or [],
            metadata=metadata or {},
        )

    def merge_extractions(
        self,
        title: str,
        extractions: List[Dict[str, Any]],
        metadata: Optional[Dict[str, Any]] = None,
    ) -> ExtractedDocument:
        """Merge multiple browser extractions into a single document.

        Each extraction dict should have: url, title, text (and optionally links).
        """
        sections = []
        all_urls = []
        all_links = []

        for ext in extractions:
            url = ext.get("url", "")
            ext_title = ext.get("title", url)
            text = ext.get("text", "")

            if url:
                all_urls.append(url)
            if ext.get("links"):
                all_links.extend(ext["links"])

            sections.append(f"### {ext_title}\n\n{text}")

        content = "\n\n---\n\n".join(sections)

        return ExtractedDocument(
            title=title,
            content=content,
            source_urls=all_urls,
            links=list(dict.fromkeys(all_links)),  # dedupe preserving order
            metadata={
                **(metadata or {}),
                "extraction_count": len(extractions),
                "total_chars": len(content),
            },
        )

    # ── Local Save ─────────────────────────────────────────────────────

    def save_markdown(self, doc: ExtractedDocument, path: Optional[str] = None) -> str:
        """Save document as markdown file. Returns the file path."""
        if path is None:
            path = str(self.output_dir / f"{doc.doc_id}.md")
        out = Path(path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(doc.to_markdown(), encoding="utf-8")
        logger.info("Saved markdown: %s (%d bytes)", path, out.stat().st_size)
        return str(out)

    def save_plain_text(self, doc: ExtractedDocument, path: Optional[str] = None) -> str:
        """Save document as plain text file."""
        if path is None:
            path = str(self.output_dir / f"{doc.doc_id}.txt")
        out = Path(path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(doc.to_plain_text(), encoding="utf-8")
        logger.info("Saved plain text: %s", path)
        return str(out)

    def save_json(self, doc: ExtractedDocument, path: Optional[str] = None) -> str:
        """Save document as structured JSON."""
        if path is None:
            path = str(self.output_dir / f"{doc.doc_id}.json")
        out = Path(path)
        out.parent.mkdir(parents=True, exist_ok=True)
        data = {
            "doc_id": doc.doc_id,
            "title": doc.title,
            "content": doc.content,
            "source_urls": doc.source_urls,
            "links": doc.links[:100],
            "screenshots": doc.screenshots,
            "metadata": doc.metadata,
            "created_at": doc.created_at,
        }
        out.write_text(json.dumps(data, indent=2), encoding="utf-8")
        logger.info("Saved JSON: %s", path)
        return str(out)

    def save_docx(self, doc: ExtractedDocument, path: Optional[str] = None) -> str:
        """Save document as DOCX file.

        Requires python-docx: pip install python-docx
        Falls back to markdown if python-docx is not installed.
        """
        if path is None:
            path = str(self.output_dir / f"{doc.doc_id}.docx")

        try:
            from docx import Document as DocxDocument
            from docx.shared import Inches, Pt
        except ImportError:
            logger.warning("python-docx not installed, falling back to markdown")
            md_path = path.replace(".docx", ".md")
            return self.save_markdown(doc, md_path)

        docx_doc = DocxDocument()

        # Title
        docx_doc.add_heading(doc.title, level=0)

        # Metadata
        if doc.metadata or doc.source_urls:
            docx_doc.add_heading("Document Info", level=1)
            p = docx_doc.add_paragraph()
            p.add_run(f"Generated: {doc.created_at}\n").italic = True
            p.add_run(f"Doc ID: {doc.doc_id}\n").italic = True
            if doc.source_urls:
                p.add_run(f"Sources: {len(doc.source_urls)}\n").italic = True

        # Content — split on markdown headers and render
        docx_doc.add_heading("Content", level=1)
        for line in doc.content.split("\n"):
            stripped = line.strip()
            if stripped.startswith("### "):
                docx_doc.add_heading(stripped[4:], level=3)
            elif stripped.startswith("## "):
                docx_doc.add_heading(stripped[3:], level=2)
            elif stripped.startswith("# "):
                docx_doc.add_heading(stripped[2:], level=1)
            elif stripped == "---":
                docx_doc.add_paragraph("─" * 40)
            elif stripped:
                docx_doc.add_paragraph(stripped)

        # Sources
        if doc.source_urls:
            docx_doc.add_heading("Sources", level=1)
            for i, url in enumerate(doc.source_urls, 1):
                docx_doc.add_paragraph(f"{i}. {url}")

        out = Path(path)
        out.parent.mkdir(parents=True, exist_ok=True)
        docx_doc.save(str(out))
        logger.info("Saved DOCX: %s", path)
        return str(out)

    # ── GitHub Push ────────────────────────────────────────────────────

    def push_to_github(
        self,
        doc: ExtractedDocument,
        path: str,
        branch: str = "main",
        commit_message: Optional[str] = None,
        format: str = "markdown",
    ) -> Dict[str, Any]:
        """Push document to GitHub as a file.

        Args:
            doc: The document to push.
            path: File path in the repo (e.g., "docs/report.md").
            branch: Target branch.
            commit_message: Commit message (auto-generated if None).
            format: Output format — "markdown", "json", or "text".

        Returns:
            Dict with success, url, sha, and response details.
        """
        if not self.github_token:
            return {"success": False, "error": "No GitHub token configured"}
        if not self.github_repo:
            return {"success": False, "error": "No GitHub repo configured"}

        if format == "json":
            content_str = json.dumps({
                "doc_id": doc.doc_id,
                "title": doc.title,
                "content": doc.content,
                "source_urls": doc.source_urls,
                "metadata": doc.metadata,
                "created_at": doc.created_at,
            }, indent=2)
        elif format == "text":
            content_str = doc.to_plain_text()
        else:
            content_str = doc.to_markdown()

        if commit_message is None:
            commit_message = f"docs: add {doc.title} via AetherBrowse DocHandler"

        import base64
        encoded = base64.b64encode(content_str.encode("utf-8")).decode("ascii")

        # Check if file already exists (to get its SHA for update)
        existing_sha = self._get_file_sha(path, branch)

        api_url = f"https://api.github.com/repos/{self.github_repo}/contents/{path}"
        payload: Dict[str, Any] = {
            "message": commit_message,
            "content": encoded,
            "branch": branch,
        }
        if existing_sha:
            payload["sha"] = existing_sha

        try:
            result = self._github_api("PUT", api_url, payload)
            file_url = result.get("content", {}).get("html_url", "")
            file_sha = result.get("content", {}).get("sha", "")
            logger.info("Pushed to GitHub: %s → %s", path, file_url)
            return {
                "success": True,
                "url": file_url,
                "sha": file_sha,
                "path": path,
                "branch": branch,
                "action": "updated" if existing_sha else "created",
            }
        except Exception as e:
            logger.error("GitHub push failed: %s", e)
            return {"success": False, "error": str(e)}

    def push_to_github_issue(
        self,
        doc: ExtractedDocument,
        labels: Optional[List[str]] = None,
    ) -> Dict[str, Any]:
        """Create a GitHub issue from the document content.

        Returns:
            Dict with success, url, issue_number.
        """
        if not self.github_token or not self.github_repo:
            return {"success": False, "error": "GitHub not configured"}

        api_url = f"https://api.github.com/repos/{self.github_repo}/issues"
        payload = {
            "title": doc.title,
            "body": doc.to_markdown(),
            "labels": labels or ["aetherbrowse", "auto-generated"],
        }

        try:
            result = self._github_api("POST", api_url, payload)
            return {
                "success": True,
                "url": result.get("html_url", ""),
                "issue_number": result.get("number"),
            }
        except Exception as e:
            return {"success": False, "error": str(e)}

    # ── GitHub Helpers ─────────────────────────────────────────────────

    def _get_file_sha(self, path: str, branch: str) -> Optional[str]:
        """Get the SHA of an existing file on GitHub (needed for updates)."""
        api_url = f"https://api.github.com/repos/{self.github_repo}/contents/{path}?ref={branch}"
        try:
            result = self._github_api("GET", api_url)
            return result.get("sha")
        except Exception:
            return None

    def _github_api(
        self, method: str, url: str, payload: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """Make a GitHub API request."""
        headers = {
            "Authorization": f"Bearer {self.github_token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        }

        data = None
        if payload is not None:
            data = json.dumps(payload).encode("utf-8")
            headers["Content-Type"] = "application/json"

        req = urllib.request.Request(url=url, data=data, method=method, headers=headers)

        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                body = resp.read().decode("utf-8")
                return json.loads(body) if body else {}
        except urllib.error.HTTPError as exc:
            body = exc.read().decode("utf-8", errors="replace")
            raise RuntimeError(f"GitHub API {method} {url}: HTTP {exc.code}: {body}") from exc
