"""
AI Brain Mapping Module - Python Reference Implementation

Multi-Vectored Quasi-Space Architecture with Lattice Mesh Integration.
Unifies all SCBE-AETHERMOORE components into a single coherent "AI brain"
architecture operating across a 21D manifold.

Version: 1.1.0 (Reference - canonical implementation is TypeScript)
"""

from .unified_state import UnifiedBrainState, safe_poincare_embed, hyperbolic_distance_safe
from .detection import (
    detect_phase_distance,
    detect_curvature_accumulation,
    detect_threat_lissajous,
    detect_decimal_drift,
    detect_six_tonic,
    run_combined_detection,
)
from .bft_consensus import BFTConsensus
from .multiscale_spectrum import (
    analyze_trajectory,
    analyze_subsystem,
    multiscale_spectrum_features,
    sliding_window_analysis,
    MultiscaleReport,
    ScaleFeatures,
)
from .mirror_shift import (
    analyze_transition,
    compute_dual_ternary,
    dual_ternary_trajectory,
    mirror_shift,
    mirror_asymmetry_score,
    quantize_ternary,
    refactor_align,
    MirrorAnalysis,
    MirrorShiftResult,
    AlignmentResult,
)
from .governance_adapter import (
    MicroStateType,
    MicroStateCensus,
    census_from_ternary,
    check_valence,
    AsymmetryTracker,
    flux_contract,
    GovernanceVerdict,
    evaluate_governance,
    evaluate_trajectory_governance,
)
from .fsgs import (
    GovernanceSymbol,
    GovernanceMode,
    HybridState,
    symbol_from_bits,
    mode_transition,
    hybrid_step,
    verdict_to_symbol,
    analyze_control_sequence,
    simulate_trajectory,
    ControlSequenceStats,
    TrajectorySimulation,
)
from .hamiltonian_braid import (
    PHASE_STATES,
    phase_label,
    valid_transition,
    valid_neighbors,
    transition_matrix,
    phase_deviation,
    RailPoint,
    Rail,
    make_rail_from_trajectory,
    nearest_rail_point,
    braid_distance,
    harmonic_cost,
    harmonic_cost_gradient,
    constraint_project,
    braid_step,
    simulate_braid,
    BraidStepResult,
    BraidTrajectory,
)
from .dual_ternary import (
    DualTernarySystem,
    DualTernaryState,
    DualTernaryConfig,
    FULL_STATE_SPACE,
    compute_state_energy,
    state_index,
    state_from_index,
    transition,
    encode_to_dual_ternary,
    encode_sequence as encode_dual_ternary_sequence,
    compute_spectrum as compute_dual_ternary_spectrum,
    estimate_fractal_dimension as estimate_ternary_fractal_dimension,
)
from .dual_lattice import (
    DualLatticeSystem,
    DualLatticeConfig,
    Lattice6D,
    Lattice3D,
    PhasonShift,
    static_projection,
    dynamic_transform,
    generate_aperiodic_mesh,
    apply_phason_shift,
    estimate_fractal_dimension as estimate_lattice_fractal_dimension,
    lattice_norm_6d,
    lattice_distance_3d,
)
from .hamiltonian_braid import (
    EPS as BRAID_EPS,
    phase_label,
    valid_transition,
    valid_neighbors,
    transition_matrix,
    phase_deviation,
    RailPoint,
    Rail,
    make_rail_from_trajectory,
    nearest_rail_point,
    braid_distance,
    harmonic_cost,
    harmonic_cost_gradient,
    ConstraintProjection,
    constraint_project,
    BraidStepResult,
    braid_step,
    BraidTrajectory,
    simulate_braid,
)

from .circuit_flow import (
    PolyDidacticCircuit,
    CircuitNode,
    CircuitEdge,
    CircuitStep,
    CircuitTrace,
    Zone,
    FluxGate,
    GovernanceAction,
    harmonic_wall_cost,
    classify_trust_ring,
    classify_intent_tongue,
    create_circuit,
    TONGUE_WEIGHTS,
    TONGUE_PHASES,
)
from .cymatic_voxel_net import (
    CymaticVoxelNet,
    NODAL_THRESHOLD,
    REALM_CENTERS,
    SACRED_TONGUES,
    TONGUE_DIMENSION_MAP,
    VOXEL_DIMS,
    chladni_6d,
    classify_zone,
    dominant_tongue,
    estimate_nodal_density,
)

__all__ = [
    "UnifiedBrainState",
    "safe_poincare_embed",
    "hyperbolic_distance_safe",
    "detect_phase_distance",
    "detect_curvature_accumulation",
    "detect_threat_lissajous",
    "detect_decimal_drift",
    "detect_six_tonic",
    "run_combined_detection",
    "BFTConsensus",
    # Multiscale Spectrum Analysis
    "analyze_trajectory",
    "analyze_subsystem",
    "multiscale_spectrum_features",
    "sliding_window_analysis",
    "MultiscaleReport",
    "ScaleFeatures",
    # Mirror Shift + Refactor Align
    "analyze_transition",
    "compute_dual_ternary",
    "dual_ternary_trajectory",
    "mirror_shift",
    "mirror_asymmetry_score",
    "quantize_ternary",
    "refactor_align",
    "MirrorAnalysis",
    "MirrorShiftResult",
    "AlignmentResult",
    # Governance Adapter (6-state dual propagation)
    "MicroStateType",
    "MicroStateCensus",
    "census_from_ternary",
    "check_valence",
    "AsymmetryTracker",
    "flux_contract",
    "GovernanceVerdict",
    "evaluate_governance",
    "evaluate_trajectory_governance",
    # FSGS Hybrid Dynamical System (4-symbol control alphabet)
    "GovernanceSymbol",
    "GovernanceMode",
    "HybridState",
    "symbol_from_bits",
    "mode_transition",
    "hybrid_step",
    "verdict_to_symbol",
    "analyze_control_sequence",
    "simulate_trajectory",
    "ControlSequenceStats",
    "TrajectorySimulation",
    # Hamiltonian Braid Dynamics
    "PHASE_STATES",
    "phase_label",
    "valid_transition",
    "valid_neighbors",
    "transition_matrix",
    "phase_deviation",
    "RailPoint",
    "Rail",
    "make_rail_from_trajectory",
    "nearest_rail_point",
    "braid_distance",
    "harmonic_cost",
    "harmonic_cost_gradient",
    "constraint_project",
    "braid_step",
    "simulate_braid",
    "BraidStepResult",
    "BraidTrajectory",
    # Dual Ternary
    "DualTernarySystem",
    "DualTernaryState",
    "DualTernaryConfig",
    "FULL_STATE_SPACE",
    "compute_state_energy",
    "state_index",
    "state_from_index",
    "transition",
    "encode_to_dual_ternary",
    "encode_dual_ternary_sequence",
    "compute_dual_ternary_spectrum",
    "estimate_ternary_fractal_dimension",
    # Dual Lattice
    "DualLatticeSystem",
    "DualLatticeConfig",
    "Lattice6D",
    "Lattice3D",
    "PhasonShift",
    "static_projection",
    "dynamic_transform",
    "generate_aperiodic_mesh",
    "apply_phason_shift",
    "estimate_lattice_fractal_dimension",
    "lattice_norm_6d",
    "lattice_distance_3d",
    # Hamiltonian Braid
    "BRAID_EPS",
    "phase_label",
    "valid_transition",
    "valid_neighbors",
    "transition_matrix",
    "phase_deviation",
    "RailPoint",
    "Rail",
    "make_rail_from_trajectory",
    "nearest_rail_point",
    "braid_distance",
    "harmonic_cost",
    "harmonic_cost_gradient",
    "ConstraintProjection",
    "constraint_project",
    "BraidStepResult",
    "braid_step",
    "BraidTrajectory",
    "simulate_braid",
    # Poly-Didactic Circuit Flow
    "PolyDidacticCircuit",
    "CircuitNode",
    "CircuitEdge",
    "CircuitStep",
    "CircuitTrace",
    "Zone",
    "FluxGate",
    "GovernanceAction",
    "harmonic_wall_cost",
    "classify_trust_ring",
    "classify_intent_tongue",
    "create_circuit",
    "TONGUE_WEIGHTS",
    "TONGUE_PHASES",
    # Cymatic Voxel Net
    "CymaticVoxelNet",
    "NODAL_THRESHOLD",
    "REALM_CENTERS",
    "SACRED_TONGUES",
    "TONGUE_DIMENSION_MAP",
    "VOXEL_DIMS",
    "chladni_6d",
    "classify_zone",
    "dominant_tongue",
    "estimate_nodal_density",
]
