#!/usr/bin/env bash
set -euo pipefail

# CI Auto-Fix — Local version
# Usage:
#   ./scripts/ci/fix_ci_local.sh              # Fix latest failed run
#   ./scripts/ci/fix_ci_local.sh --run-id 123 # Fix specific run
#   ./scripts/ci/fix_ci_local.sh --dry-run    # Preview only

REPO_ROOT="$(git rev-parse --show-toplevel)"
MAX_BUDGET="${CI_FIX_BUDGET:-1.00}"

echo ""
echo "============================================"
echo "  SCBE CI Auto-Fix (Local)"
echo "============================================"

# Step 1: Detect failures
echo ""
echo "=== Step 1: Detecting failures ==="
REPORT=$(python "$REPO_ROOT/scripts/ci/detect_failures.py" "$@" --json 2>/dev/null) || {
    echo "No failures detected or detection error."
    exit 0
}

FAILURE_COUNT=$(echo "$REPORT" | python3 -c "import json,sys; print(json.load(sys.stdin).get('failure_count',0))")
RUN_ID=$(echo "$REPORT" | python3 -c "import json,sys; print(json.load(sys.stdin).get('run_id',0))")

if [ "$FAILURE_COUNT" = "0" ]; then
    echo "No classified failures found."
    exit 0
fi

echo "Found $FAILURE_COUNT failure(s) in run $RUN_ID"

# Step 2: Try deterministic fixes first
echo ""
echo "=== Step 2: Applying deterministic fixes ==="

NEEDS_BLACK=$(echo "$REPORT" | python3 -c "
import json,sys
d = json.load(sys.stdin)
print('yes' if any(f.get('fix_strategy')=='black_format' for f in d.get('failures',[])) else 'no')
")

if [ "$NEEDS_BLACK" = "yes" ]; then
    echo "  Running Black formatter..."
    python -m black --target-version py311 --line-length 120 src/ tests/ 2>/dev/null || true
fi

# Check if deterministic fixes resolved everything
if [ -n "$(git diff --stat)" ]; then
    echo "  Deterministic fixes applied. Check if CI would pass now."
fi

# Step 3: Dispatch AI agent for complex fixes
echo ""
echo "=== Step 3: Dispatching AI agent ==="

# Build targeted prompt from failure details
FAILURES_TEXT=$(echo "$REPORT" | python3 -c "
import json,sys
d = json.load(sys.stdin)
for f in d.get('failures',[]):
    s = f.get('fix_strategy','')
    if s in ('black_format','npm_audit_fix'): continue  # Skip deterministic
    print(f'[{f.get(\"category\",\"\")}] {f.get(\"description\",\"\")}: {f.get(\"raw_match\",\"\")[:150]}')
    if f.get('file_path'):
        print(f'  File: {f[\"file_path\"]}:{f.get(\"line_number\",\"\")}')
")

if [ -z "$FAILURES_TEXT" ]; then
    echo "  All failures are deterministic (already fixed above)."
else
    PROMPT="Fix the following CI failures in the SCBE-AETHERMOORE repo.

Failures:
$FAILURES_TEXT

Instructions:
1. Read each failing file
2. Make the MINIMAL change to fix each error
3. Do NOT refactor unrelated code
4. Common fixes: add type assertions, fix imports, add skip guards for missing deps"

    if command -v claude &>/dev/null; then
        echo "  Using Claude Code CLI (budget: \$$MAX_BUDGET)..."
        claude -p "$PROMPT" --max-turns 10 || echo "  Claude fix attempt completed"
    elif command -v codex &>/dev/null; then
        echo "  Using Codex CLI..."
        codex exec "$PROMPT" || echo "  Codex fix attempt completed"
    else
        echo "  No AI agent found. Manual fix needed."
        echo "  Suggested commands:"
        echo "$REPORT" | python3 -c "
import json,sys
d = json.load(sys.stdin)
for cmd in d.get('fix_commands',[]):
    print(f'    \$ {cmd}')
"
        exit 1
    fi
fi

# Step 4: Check for changes and create PR
echo ""
echo "=== Step 4: Creating fix PR ==="

if [ -z "$(git diff --stat)" ]; then
    echo "  No changes made. Manual intervention needed."
    exit 1
fi

echo "  Changes detected:"
git diff --stat

read -p "  Create fix branch and PR? [y/N] " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    BRANCH="fix/ci-auto-fix-${RUN_ID}"
    git checkout -b "$BRANCH" 2>/dev/null || git checkout "$BRANCH"
    git add -A
    git commit -m "fix(ci): auto-fix $FAILURE_COUNT failure(s) from run $RUN_ID

Automated fix generated by scripts/ci/fix_ci_local.sh

Co-Authored-By: Claude Opus 4.6 (1M context) <noreply@anthropic.com>"
    git push -u origin "$BRANCH"

    gh pr create \
        --title "fix(ci): auto-fix $FAILURE_COUNT failure(s) from run $RUN_ID" \
        --body "## Automated CI Fix

**Run**: $RUN_ID
**Failures fixed**: $FAILURE_COUNT

$(echo "$FAILURES_TEXT" | sed 's/^/- /')

Generated by \`scripts/ci/fix_ci_local.sh\`

🤖 Generated with [Claude Code](https://claude.com/claude-code)" \
        --base main

    echo "  PR created!"
else
    echo "  Skipped PR creation. Changes are unstaged."
fi
