"""Export tax results as text summary and PDF (1040-style layout).

PDF generation uses only Python stdlib — outputs a PostScript-derived PDF
with fixed-width layout that mirrors the 1040 line structure.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from .models import TaxInput, TaxResult


def _currency(amount: float) -> str:
    """Format as $X,XXX.XX."""
    if amount < 0:
        return f"-${abs(amount):,.2f}"
    return f"${amount:,.2f}"


def _pct(rate: float) -> str:
    return f"{rate * 100:.1f}%"


def generate_text_summary(inp: TaxInput, result: TaxResult) -> str:
    """Generate a human-readable text summary of the 1040 computation."""
    tp = inp.taxpayer
    lines = []
    w = lines.append
    sep = "=" * 72

    w(sep)
    w("  FEDERAL TAX RETURN SUMMARY — Tax Year 2025")
    w("  Generated by SCBE Tax Tool (for review, not official filing)")
    w(sep)
    w("")
    w(f"  Taxpayer:       {tp.first_name} {tp.last_name}")
    w(f"  SSN:            {tp.ssn}")
    w(f"  Filing Status:  {tp.filing_status.value.replace('_', ' ').title()}")
    if tp.address:
        w(f"  Address:        {tp.address}, {tp.city}, {tp.state} {tp.zip_code}")
    w("")

    # --- W-2 Summary ---
    if inp.w2s:
        w("  W-2 INCOME")
        w("  " + "-" * 68)
        for i, w2 in enumerate(inp.w2s, 1):
            w(f"    W-2 #{i}: {w2.employer_name}")
            w(f"      Wages (Box 1):              {_currency(w2.wages)}")
            w(f"      Federal Withheld (Box 2):    {_currency(w2.federal_tax_withheld)}")
            w(f"      SS Wages / Tax (Box 3/4):    {_currency(w2.social_security_wages)} / {_currency(w2.social_security_tax)}")
            w(f"      Medicare Wages / Tax (5/6):   {_currency(w2.medicare_wages)} / {_currency(w2.medicare_tax)}")
            if w2.state:
                w(f"      State: {w2.state}  Wages: {_currency(w2.state_wages)}  Withheld: {_currency(w2.state_tax_withheld)}")
        w("")

    # --- 1099 Summary ---
    if inp.income_1099s:
        w("  1099 INCOME")
        w("  " + "-" * 68)
        for inc in inp.income_1099s:
            w(f"    1099-{inc.type:4s}  {inc.payer_name:30s}  {_currency(inc.amount)}")
        w("")

    # --- 1040 Lines ---
    w("  FORM 1040 — COMPUTATION")
    w("  " + "-" * 68)
    w(f"   1   Wages, salaries, tips              {_currency(result.total_wages):>20s}")
    w(f"   2b  Taxable interest                   {_currency(result.interest_income):>20s}")
    w(f"   3b  Ordinary dividends                 {_currency(result.dividend_income):>20s}")
    w(f"   8   Other income                       {_currency(result.other_income):>20s}")
    w(f"   9   TOTAL INCOME                       {_currency(result.total_income):>20s}")
    w(f"  10   Adjustments to income              {_currency(result.adjustments):>20s}")
    w(f"  11   ADJUSTED GROSS INCOME (AGI)        {_currency(result.adjusted_gross_income):>20s}")
    w("")
    if result.deduction_used == "standard":
        w(f"  12   Standard deduction                 {_currency(result.standard_deduction):>20s}")
    else:
        w(f"  12   Itemized deductions (Sch A)         {_currency(result.itemized_deduction):>20s}")
    w(f"  14   Total deductions                   {_currency(result.total_deductions):>20s}")
    w(f"  15   TAXABLE INCOME                     {_currency(result.taxable_income):>20s}")
    w("")
    w(f"  16   Tax                                {_currency(result.tax):>20s}")
    if result.total_credits > 0:
        w(f"  19   Child tax credit                   {_currency(result.child_tax_credit):>20s}")
        w(f"  21   Other credits                      {_currency(result.other_credits):>20s}")
    w(f"       Tax after credits                  {_currency(result.tax_after_credits):>20s}")
    if result.self_employment_tax > 0:
        w(f"  23   Self-employment tax                {_currency(result.self_employment_tax):>20s}")
    w(f"  24   TOTAL TAX                          {_currency(result.total_tax):>20s}")
    w("")
    w(f"  25   Federal income tax withheld         {_currency(result.federal_withheld):>20s}")
    if result.estimated_payments > 0:
        w(f"  26   Estimated payments + credits        {_currency(result.estimated_payments):>20s}")
    w(f"  33   TOTAL PAYMENTS                     {_currency(result.total_payments):>20s}")
    w("")

    w("  " + "=" * 68)
    if result.refund > 0:
        w(f"  34   REFUND                             {_currency(result.refund):>20s}")
    elif result.amount_owed > 0:
        w(f"  37   AMOUNT YOU OWE                     {_currency(result.amount_owed):>20s}")
    else:
        w(f"       BALANCED — no refund, no amount owed")
    w("  " + "=" * 68)
    w("")

    # --- Rate Summary ---
    w("  TAX RATE ANALYSIS")
    w("  " + "-" * 68)
    w(f"    Effective tax rate:   {_pct(result.effective_rate)}")
    w(f"    Marginal bracket:    {_pct(result.marginal_rate)}")
    w("")
    w("    Bracket Breakdown:")
    for b in result.bracket_breakdown:
        w(f"      {b['rate']:>4s}  on  {_currency(b['income_in_bracket']):>14s}  =  {_currency(b['tax']):>12s}  ({b['bracket']})")
    w("")

    w(sep)
    w("  DISCLAIMER: This is a calculation tool, not tax advice.")
    w("  Verify all figures before filing. Consult a tax professional")
    w("  for complex situations.")
    w(sep)

    return "\n".join(lines)


def generate_json_output(inp: TaxInput, result: TaxResult) -> str:
    """Generate machine-readable JSON of the full computation."""
    from dataclasses import asdict

    output = {
        "tax_year": 2025,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "taxpayer": {
            "name": f"{inp.taxpayer.first_name} {inp.taxpayer.last_name}",
            "filing_status": inp.taxpayer.filing_status.value,
        },
        "result": asdict(result),
    }
    return json.dumps(output, indent=2, default=str)


# ---------------------------------------------------------------------------
# Minimal PDF generator (stdlib only — no external dependencies)
# Generates a simple, printable PDF with the tax summary text.
# ---------------------------------------------------------------------------

_PDF_HEADER = """%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
"""


def _pdf_page_stream(text_lines: list[str], page_width: float = 612, page_height: float = 792) -> bytes:
    """Build a single-page PDF content stream for Courier text."""
    font_size = 9
    leading = 11
    margin_left = 36
    margin_top = page_height - 36

    stream_lines = [f"BT /F1 {font_size} Tf"]
    y = margin_top
    for line in text_lines:
        if y < 36:
            break  # Simple: stop if we run out of page
        escaped = line.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")
        stream_lines.append(f"{margin_left} {y:.1f} Td ({escaped}) Tj")
        y -= leading
        stream_lines.append(f"0 -{leading} Td")

    # Reset: we used relative Td after the first absolute one — fix with absolute positioning
    # Actually let's redo with absolute positioning per line
    stream_lines = [f"BT /F1 {font_size} Tf"]
    y = margin_top
    for line in text_lines:
        if y < 36:
            break
        escaped = line.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")
        stream_lines.append(f"1 0 0 1 {margin_left} {y:.1f} Tm ({escaped}) Tj")
        y -= leading

    stream_lines.append("ET")
    return "\n".join(stream_lines).encode("latin-1", errors="replace")


def generate_pdf(inp: TaxInput, result: TaxResult, output_path: str | Path) -> Path:
    """Generate a minimal printable PDF with the tax summary."""
    text = generate_text_summary(inp, result)
    all_lines = text.split("\n")

    # Split into pages (max ~65 lines per page at 9pt/11pt leading on letter)
    max_lines_per_page = 65
    pages: list[list[str]] = []
    for i in range(0, len(all_lines), max_lines_per_page):
        pages.append(all_lines[i : i + max_lines_per_page])

    # Build PDF manually
    objects: list[bytes] = []
    offsets: list[int] = []
    pdf = bytearray()

    def add_obj(content: bytes) -> int:
        obj_num = len(objects) + 1
        offsets.append(len(pdf))
        obj_bytes = f"{obj_num} 0 obj\n".encode() + content + b"\nendobj\n"
        pdf.extend(obj_bytes)
        objects.append(obj_bytes)
        return obj_num

    # Header
    pdf.extend(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")

    # Object 1: Catalog
    catalog_num = add_obj(b"<< /Type /Catalog /Pages 2 0 R >>")

    # Object 2: Pages (placeholder — we'll fix the Kids array)
    pages_placeholder_offset = len(pdf)
    pages_obj_index = len(objects)
    add_obj(b"<< /Type /Pages /Kids [] /Count 0 >>")  # Placeholder

    # Object 3: Font
    font_num = add_obj(b"<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>")

    # Build each page
    page_obj_nums = []
    for page_lines in pages:
        stream_data = _pdf_page_stream(page_lines)
        stream_num = add_obj(
            b"<< /Length " + str(len(stream_data)).encode() + b" >>\nstream\n" + stream_data + b"\nendstream"
        )
        page_num = add_obj(
            f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
            f"/Contents {stream_num} 0 R "
            f"/Resources << /Font << /F1 {font_num} 0 R >> >> >>".encode()
        )
        page_obj_nums.append(page_num)

    # Now rewrite Pages object with actual kids
    kids_str = " ".join(f"{n} 0 R" for n in page_obj_nums)
    new_pages_obj = f"<< /Type /Pages /Kids [{kids_str}] /Count {len(page_obj_nums)} >>".encode()

    # We need to rebuild the PDF with the corrected Pages object
    # Simpler approach: rebuild from scratch
    pdf2 = bytearray()
    offsets2: list[int] = []
    obj_contents: list[bytes] = []

    pdf2.extend(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")

    def add_obj2(content: bytes) -> int:
        num = len(obj_contents) + 1
        offsets2.append(len(pdf2))
        obj_bytes = f"{num} 0 obj\n".encode() + content + b"\nendobj\n"
        pdf2.extend(obj_bytes)
        obj_contents.append(content)
        return num

    # 1: Catalog
    add_obj2(b"<< /Type /Catalog /Pages 2 0 R >>")

    # 2: Pages (with correct kids — we know page nums will be 4,6,8... for stream+page pairs starting at obj 4)
    # Font is obj 3, then pairs of (stream, page) for each page
    page_nums = [3 + 1 + i * 2 + 1 for i in range(len(pages))]  # 5, 7, 9, ...
    kids_str = " ".join(f"{n} 0 R" for n in page_nums)
    add_obj2(f"<< /Type /Pages /Kids [{kids_str}] /Count {len(pages)} >>".encode())

    # 3: Font
    font_ref = add_obj2(b"<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>")

    # Pages
    for page_lines in pages:
        stream_data = _pdf_page_stream(page_lines)
        stream_ref = add_obj2(
            b"<< /Length " + str(len(stream_data)).encode() + b" >>\nstream\n" + stream_data + b"\nendstream"
        )
        add_obj2(
            f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
            f"/Contents {stream_ref} 0 R "
            f"/Resources << /Font << /F1 {font_ref} 0 R >> >> >>".encode()
        )

    # Cross-reference table
    xref_offset = len(pdf2)
    pdf2.extend(b"xref\n")
    pdf2.extend(f"0 {len(obj_contents) + 1}\n".encode())
    pdf2.extend(b"0000000000 65535 f \n")
    for off in offsets2:
        pdf2.extend(f"{off:010d} 00000 n \n".encode())

    # Trailer
    pdf2.extend(f"trailer\n<< /Size {len(obj_contents) + 1} /Root 1 0 R >>\n".encode())
    pdf2.extend(f"startxref\n{xref_offset}\n%%EOF\n".encode())

    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_bytes(bytes(pdf2))
    return out
