"""SCBE transference gate: bytes/text -> Python-safe UTF-8.

This is the Rosetta/lexicon bridge for encoding problems:

    raw file bytes
      -> detect UTF family / BOM
      -> canonical UTF-8 text without BOM
      -> Python-safe source or normalized file
      -> receipt with hashes

It deliberately does not pretend arbitrary text is STIB. STIB is the executable
opcode/program binary lane. This module is the text transference lane that lets
Python tools consume Windows/UTF/BOM files safely.

Usage:
    python -m python.scbe.transference_gate packet path.json
    python -m python.scbe.transference_gate normalize path.json --out path.pyutf8.json
    python -m python.scbe.transference_gate emit-python path.txt --out payload.py
"""

from __future__ import annotations

import argparse
import hashlib
import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Optional


@dataclass(frozen=True)
class TransferPacket:
    schema: str
    source_path: str
    detected_encoding: str
    bom: str
    raw_sha256: str
    utf8_sha256: str
    raw_bytes: int
    text_chars: int
    python_read_encoding: str
    python_safe: bool
    notes: list[str]


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def detect_utf_encoding(data: bytes) -> tuple[str, str, list[str]]:
    """Return (encoding, bom_label, notes) for likely UTF-family text."""

    notes: list[str] = []
    if data.startswith(b"\xff\xfe\x00\x00"):
        return "utf-32-le", "utf-32-le-bom", notes
    if data.startswith(b"\x00\x00\xfe\xff"):
        return "utf-32-be", "utf-32-be-bom", notes
    if data.startswith(b"\xef\xbb\xbf"):
        return "utf-8-sig", "utf-8-bom", notes
    if data.startswith(b"\xff\xfe"):
        return "utf-16-le", "utf-16-le-bom", notes
    if data.startswith(b"\xfe\xff"):
        return "utf-16-be", "utf-16-be-bom", notes

    try:
        data.decode("utf-8")
        return "utf-8", "none", notes
    except UnicodeDecodeError:
        pass

    # PowerShell/Windows text can be UTF-16LE without a BOM. Detect by NUL
    # distribution rather than guessing cp1252 first.
    sample = data[:4096]
    if len(sample) >= 4:
        even_nuls = sum(1 for b in sample[0::2] if b == 0)
        odd_nuls = sum(1 for b in sample[1::2] if b == 0)
        pairs = max(1, len(sample) // 2)
        if odd_nuls / pairs > 0.30 and even_nuls / pairs < 0.05:
            notes.append("utf-16-le inferred from odd-byte NUL pattern")
            return "utf-16-le", "none-inferred", notes
        if even_nuls / pairs > 0.30 and odd_nuls / pairs < 0.05:
            notes.append("utf-16-be inferred from even-byte NUL pattern")
            return "utf-16-be", "none-inferred", notes

    raise UnicodeError("input is not valid UTF-8/16/32 text; refusing lossy decode")


def decode_text(data: bytes) -> tuple[str, str, str, list[str]]:
    encoding, bom, notes = detect_utf_encoding(data)
    text = data.decode(encoding, errors="strict")
    if text.startswith("\ufeff"):
        text = text[1:]
        notes.append("leading BOM codepoint removed")
    return text, encoding, bom, notes


def packet_for_path(path: Path) -> tuple[TransferPacket, str, bytes]:
    raw = path.read_bytes()
    text, encoding, bom, notes = decode_text(raw)
    utf8 = text.encode("utf-8")
    packet = TransferPacket(
        schema="scbe.transference_gate.v1",
        source_path=str(path),
        detected_encoding=encoding,
        bom=bom,
        raw_sha256=_sha256(raw),
        utf8_sha256=_sha256(utf8),
        raw_bytes=len(raw),
        text_chars=len(text),
        python_read_encoding="utf-8",
        python_safe=True,
        notes=notes,
    )
    return packet, text, utf8


def write_normalized(src: Path, dst: Path, receipt: Optional[Path] = None) -> TransferPacket:
    packet, text, _ = packet_for_path(src)
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(text, encoding="utf-8", newline="")
    if receipt is not None:
        receipt.parent.mkdir(parents=True, exist_ok=True)
        receipt.write_text(json.dumps(asdict(packet), indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return packet


def python_source_for_text(packet: TransferPacket, text: str) -> str:
    return (
        "# -*- coding: utf-8 -*-\n"
        "# Generated by python.scbe.transference_gate. Do not edit by hand.\n"
        "SCBE_TRANSFER_PACKET = "
        + repr(asdict(packet))
        + "\n\n"
        "SCBE_TRANSFER_TEXT = "
        + repr(text)
        + "\n\n"
        "def read_text():\n"
        "    return SCBE_TRANSFER_TEXT\n"
    )


def emit_python(src: Path, dst: Optional[Path] = None) -> str:
    packet, text, _ = packet_for_path(src)
    source = python_source_for_text(packet, text)
    if dst is not None:
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text(source, encoding="utf-8", newline="\n")
    return source


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(prog="scbe-transfer", description="UTF text -> Python-safe UTF-8 gate")
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_packet = sub.add_parser("packet", help="print transference receipt as JSON")
    p_packet.add_argument("path")

    p_norm = sub.add_parser("normalize", help="write UTF-8/no-BOM normalized text")
    p_norm.add_argument("path")
    p_norm.add_argument("--out", required=True)
    p_norm.add_argument("--receipt")

    p_py = sub.add_parser("emit-python", help="emit Python source containing the decoded text")
    p_py.add_argument("path")
    p_py.add_argument("--out")

    args = parser.parse_args(argv)

    if args.cmd == "packet":
        packet, _, _ = packet_for_path(Path(args.path))
        print(json.dumps(asdict(packet), indent=2, sort_keys=True))
        return 0

    if args.cmd == "normalize":
        packet = write_normalized(
            Path(args.path),
            Path(args.out),
            Path(args.receipt) if args.receipt else None,
        )
        print(json.dumps(asdict(packet), indent=2, sort_keys=True))
        return 0

    if args.cmd == "emit-python":
        source = emit_python(Path(args.path), Path(args.out) if args.out else None)
        if not args.out:
            print(source)
        return 0

    raise AssertionError(args.cmd)


if __name__ == "__main__":
    raise SystemExit(main())
