"""
Binary Manifold — Mantissa Bit Walks Across 14 Governance Layers
=================================================================

Every float64 has 52 mantissa bits. Those bits are NOT random — they're
determined by the mathematical value. When you plot them as a walk
(1 = up, 0 = down), you get a trajectory through binary space.

14 layers × 52 bits = 728 binary digits = a 728-step walk.

The key discovery: PHI-SCALED values produce FIBONACCI-STRUCTURED binary
expansions. The mantissa bits of phi (1.618...) follow substitution rules
similar to the Fibonacci word:

    Fibonacci word: start with "1", apply 1→10, 0→1 repeatedly
    Result: 1, 10, 101, 10110, 10110101, ...

    Phi binary: 1.100111100011011...
    Note the runs: 1, 00, 111, 00, 11, 0, 11, ...
    Run lengths echo Fibonacci: 1, 2, 3, 2, 2, 1, 2, ...

Clean governance operations are phi-scaled (Sacred Tongue weights = PHI^n).
Their mantissa bits carry this Fibonacci structure.

Adversarial operations distort the phi-scaling. Their mantissa bits lose
the Fibonacci structure — the walk becomes erratic, the run lengths
become irregular, the quasicrystal order breaks down.

This is VISIBLE. Plot the walks and you can SEE the difference.

Multi-dimensional manifold interpretation:
- Each bit position IS a dimension
- The 52-bit mantissa IS a point in {0,1}^52 (a vertex of a 52D hypercube)
- 14 layers = 14 points in this hypercube
- The trajectory connecting them IS the manifold
- Project to 2D/3D for visualization

Aperiodic phases:
- Runs of 1s (up up up up) = locally periodic phase
- Transitions (1→0 or 0→1) = phase boundaries
- The PATTERN of these transitions = the quasicrystal fingerprint
- Fibonacci-like run lengths = healthy operation
- Irregular run lengths = drift / anomaly / attack

@layer All layers (transversal, binary)
@patent USPTO #63/961,403
"""

from __future__ import annotations

import hashlib
import math
import struct
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

from .tracker import (
    PHI, FIBONACCI_SEQ, TONGUE_WEIGHTS, LAYER_TONGUE_RESONANCE,
    LayerSnapshot,
)

# ---------------------------------------------------------------------------
#  Constants
# ---------------------------------------------------------------------------

MANTISSA_BITS = 52  # IEEE 754 float64
EXPONENT_BITS = 11
TOTAL_LAYER_BITS = MANTISSA_BITS * 14  # 728 bits per evaluation

# Fibonacci word reference (first 100 digits)
# Generated by: start="1", rules: 1→10, 0→1
def _fibonacci_word(n: int) -> str:
    """Generate the Fibonacci word of length n."""
    a, b = "1", "10"
    while len(b) < n:
        a, b = b, b + a
    return b[:n]

FIBONACCI_WORD_REF = _fibonacci_word(200)


# ---------------------------------------------------------------------------
#  Bit Extraction
# ---------------------------------------------------------------------------

def float_to_bits(value: float) -> Tuple[int, List[int], int]:
    """
    Extract the binary components of a float64.

    Returns: (sign_bit, mantissa_bits[52], exponent_int)
    """
    # Pack as IEEE 754 double
    raw = struct.pack("!d", value)
    as_int = int.from_bytes(raw, "big")

    sign = (as_int >> 63) & 1
    exponent = (as_int >> 52) & 0x7FF
    mantissa_int = as_int & ((1 << 52) - 1)

    # Extract individual mantissa bits (MSB first)
    mantissa_bits = []
    for i in range(51, -1, -1):
        mantissa_bits.append((mantissa_int >> i) & 1)

    return sign, mantissa_bits, exponent


def bits_to_walk(bits: List[int]) -> List[int]:
    """
    Convert binary digits to a random walk.
    1 → step up (+1), 0 → step down (-1).
    Returns cumulative positions.
    """
    walk = [0]
    for b in bits:
        step = 1 if b == 1 else -1
        walk.append(walk[-1] + step)
    return walk


def compute_runs(bits: List[int]) -> List[Tuple[int, int]]:
    """
    Compute run-length encoding: consecutive sequences of same bit.
    Returns list of (bit_value, run_length).
    """
    if not bits:
        return []
    runs = []
    current_bit = bits[0]
    current_len = 1
    for b in bits[1:]:
        if b == current_bit:
            current_len += 1
        else:
            runs.append((current_bit, current_len))
            current_bit = b
            current_len = 1
    runs.append((current_bit, current_len))
    return runs


def fibonacci_similarity(run_lengths: List[int]) -> float:
    """
    Measure how well a sequence of run lengths matches Fibonacci structure.

    The Fibonacci word has run lengths that are predominantly 1 and 2,
    with occasional 3s, following the Fibonacci ratio.

    Returns 0.0 (no similarity) to 1.0 (perfect Fibonacci structure).
    """
    if not run_lengths:
        return 0.0

    # Fibonacci word run lengths are dominated by 1s and 2s
    fib_runs = [1, 2]  # The two most common run lengths in Fibonacci word
    count_fib = sum(1 for r in run_lengths if r in fib_runs)
    fib_ratio = count_fib / len(run_lengths)

    # Also check: ratio of 1s to 2s should approach 1/phi
    ones = sum(1 for r in run_lengths if r == 1)
    twos = sum(1 for r in run_lengths if r == 2)
    if twos > 0:
        ratio = ones / twos
        ratio_score = 1.0 - min(abs(ratio - PHI) / PHI, 1.0)
    else:
        ratio_score = 0.5

    # Long runs (>3) break Fibonacci structure
    long_runs = sum(1 for r in run_lengths if r > 3)
    long_penalty = long_runs / max(len(run_lengths), 1)

    return max(0.0, fib_ratio * 0.5 + ratio_score * 0.3 - long_penalty * 0.2)


# ---------------------------------------------------------------------------
#  Data Types
# ---------------------------------------------------------------------------

@dataclass
class LayerBitProfile:
    """Binary profile for a single layer's float value."""
    layer: int
    value: float
    sign: int
    mantissa_bits: List[int]     # 52 bits
    exponent: int
    walk: List[int]              # 53 positions (52 steps + start at 0)
    runs: List[Tuple[int, int]]  # (bit, length) pairs
    run_lengths: List[int]       # Just the lengths
    ones_density: float          # Fraction of 1-bits
    fibonacci_score: float       # Similarity to Fibonacci word structure
    max_run: int                 # Longest consecutive same-bit run
    transitions: int             # Number of 0→1 or 1→0 transitions
    walk_endpoint: int           # Final position of the walk
    tongue: str

    def to_dict(self) -> Dict[str, Any]:
        return {
            "layer": self.layer,
            "value": self.value,
            "bits": "".join(str(b) for b in self.mantissa_bits),
            "ones_density": round(self.ones_density, 4),
            "fibonacci_score": round(self.fibonacci_score, 4),
            "max_run": self.max_run,
            "transitions": self.transitions,
            "walk_endpoint": self.walk_endpoint,
            "tongue": self.tongue,
        }


@dataclass
class BinaryManifold:
    """Complete binary manifold analysis for one governance evaluation."""
    layers: List[LayerBitProfile]    # 14 layer profiles
    full_walk: List[int]             # 729 positions (728 steps)
    full_bits: List[int]             # 728 bits concatenated
    full_runs: List[Tuple[int, int]]
    full_run_lengths: List[int]

    # Manifold metrics
    manifold_hash: str               # SHA-256 of all 728 bits
    total_fibonacci_score: float     # Average fibonacci similarity across layers
    walk_range: int                  # max(walk) - min(walk): how wide the walk spreads
    walk_bias: float                 # Positive = more 1s, negative = more 0s
    aperiodic_score: float           # How aperiodic is the full sequence?
    quasicrystal_quality: float      # Combined measure of order + aperiodicity
    phase_boundaries: int            # Number of transitions in the full walk
    longest_phase: int               # Longest unbroken run in full walk

    # Multi-D manifold projection
    layer_walk_endpoints: List[int]  # Where each layer's walk ends up
    manifold_dimension: int          # Estimated intrinsic dimension

    def to_dict(self) -> Dict[str, Any]:
        return {
            "manifold_hash": self.manifold_hash,
            "total_fibonacci_score": round(self.total_fibonacci_score, 4),
            "walk_range": self.walk_range,
            "walk_bias": round(self.walk_bias, 4),
            "aperiodic_score": round(self.aperiodic_score, 4),
            "quasicrystal_quality": round(self.quasicrystal_quality, 4),
            "phase_boundaries": self.phase_boundaries,
            "longest_phase": self.longest_phase,
            "layer_walk_endpoints": self.layer_walk_endpoints,
            "manifold_dimension": self.manifold_dimension,
            "layers": [l.to_dict() for l in self.layers],
            "full_bits_preview": "".join(str(b) for b in self.full_bits[:100]) + "...",
        }

    def walk_as_2d_points(self) -> List[Tuple[int, int]]:
        """Return the full walk as (step, position) pairs for plotting."""
        return [(i, pos) for i, pos in enumerate(self.full_walk)]

    def layer_boundary_positions(self) -> List[int]:
        """Return step indices where one layer ends and the next begins."""
        return [i * MANTISSA_BITS for i in range(1, 14)]


# ---------------------------------------------------------------------------
#  Binary Manifold Analyzer
# ---------------------------------------------------------------------------

class BinaryManifoldAnalyzer:
    """
    Extracts and analyzes the binary manifold of governance evaluations.

    Each evaluation's 14 layer values, when decomposed to mantissa bits,
    reveal a 728-bit trajectory through binary space. This trajectory
    has structure — phi-scaled values produce Fibonacci-like patterns.

    The analyzer detects:
    1. Fibonacci word similarity in mantissa bit patterns
    2. Aperiodic phase structure (quasicrystal quality)
    3. Run-length statistics (phase durations)
    4. Walk trajectory shape (endpoint, range, bias)
    5. Multi-layer manifold structure (dimension, clustering)
    """

    def __init__(self):
        self._history: List[BinaryManifold] = []

    def analyze(self, snapshot: LayerSnapshot) -> BinaryManifold:
        """Analyze the binary manifold of a governance evaluation."""
        layers: List[LayerBitProfile] = []
        full_bits: List[int] = []

        for layer_num in range(1, 15):
            value = snapshot.values.get(layer_num, 0.0)
            tongue = LAYER_TONGUE_RESONANCE[layer_num]

            sign, mantissa, exponent = float_to_bits(value)
            walk = bits_to_walk(mantissa)
            runs = compute_runs(mantissa)
            run_lengths = [r[1] for r in runs]
            ones = sum(mantissa)
            transitions = sum(1 for i in range(1, len(mantissa)) if mantissa[i] != mantissa[i-1])

            profile = LayerBitProfile(
                layer=layer_num,
                value=value,
                sign=sign,
                mantissa_bits=mantissa,
                exponent=exponent,
                walk=walk,
                runs=runs,
                run_lengths=run_lengths,
                ones_density=ones / MANTISSA_BITS,
                fibonacci_score=fibonacci_similarity(run_lengths),
                max_run=max(run_lengths) if run_lengths else 0,
                transitions=transitions,
                walk_endpoint=walk[-1],
                tongue=tongue,
            )
            layers.append(profile)
            full_bits.extend(mantissa)

        # Full 728-bit analysis
        full_walk = bits_to_walk(full_bits)
        full_runs = compute_runs(full_bits)
        full_run_lengths = [r[1] for r in full_runs]

        # Manifold hash — hash the 728-bit string directly
        bit_str = "".join(str(b) for b in full_bits)
        manifold_hash = hashlib.sha256(bit_str.encode()).hexdigest()[:32]

        # Fibonacci score across all layers
        total_fib = sum(l.fibonacci_score for l in layers) / 14

        # Walk statistics
        walk_max = max(full_walk)
        walk_min = min(full_walk)
        walk_range = walk_max - walk_min
        walk_bias = sum(full_bits) / len(full_bits) - 0.5  # 0 = balanced, +0.5 = all 1s

        # Aperiodicity: how non-repeating is the sequence?
        # Check for exact periodicity by looking for short repeated patterns
        aperiodic = self._measure_aperiodicity(full_bits)

        # Quasicrystal quality: ordered but aperiodic
        # High fibonacci_score (ordered) + high aperiodicity = quasicrystal
        quasicrystal = total_fib * 0.5 + aperiodic * 0.5

        # Phase boundaries in full walk
        phase_boundaries = sum(1 for i in range(1, len(full_bits)) if full_bits[i] != full_bits[i-1])

        # Longest phase
        longest_phase = max(full_run_lengths) if full_run_lengths else 0

        # Layer walk endpoints (the 14D manifold projection)
        endpoints = [l.walk_endpoint for l in layers]

        # Estimate manifold dimension using box-counting on endpoints
        manifold_dim = self._estimate_dimension(endpoints)

        manifold = BinaryManifold(
            layers=layers,
            full_walk=full_walk,
            full_bits=full_bits,
            full_runs=full_runs,
            full_run_lengths=full_run_lengths,
            manifold_hash=manifold_hash,
            total_fibonacci_score=total_fib,
            walk_range=walk_range,
            walk_bias=walk_bias,
            aperiodic_score=aperiodic,
            quasicrystal_quality=quasicrystal,
            phase_boundaries=phase_boundaries,
            longest_phase=longest_phase,
            layer_walk_endpoints=endpoints,
            manifold_dimension=manifold_dim,
        )

        self._history.append(manifold)
        return manifold

    def _measure_aperiodicity(self, bits: List[int], max_period: int = 50) -> float:
        """
        Measure how aperiodic a bit sequence is.
        Checks for exact repetition at periods 1 through max_period.
        Returns 1.0 for fully aperiodic, 0.0 for perfectly periodic.
        """
        n = len(bits)
        if n < 2:
            return 1.0

        best_match = 0.0
        for period in range(1, min(max_period, n // 2)):
            matches = sum(1 for i in range(period, n) if bits[i] == bits[i - period])
            match_ratio = matches / (n - period)
            best_match = max(best_match, match_ratio)

        # If best periodic match is high, aperiodicity is low
        return max(0.0, 1.0 - best_match)

    def _estimate_dimension(self, endpoints: List[int]) -> int:
        """
        Rough estimate of manifold intrinsic dimension from endpoint spread.
        Uses the spread of unique values as a proxy.
        """
        unique = len(set(endpoints))
        if unique <= 1:
            return 0
        elif unique <= 3:
            return 1
        elif unique <= 7:
            return 2
        else:
            return min(3, int(math.log2(unique)))

    def compare_walks(self, m1: BinaryManifold, m2: BinaryManifold) -> Dict[str, Any]:
        """
        Compare two binary manifolds — do they travel the same path?
        """
        # Bit-level Hamming distance
        hamming = sum(a != b for a, b in zip(m1.full_bits, m2.full_bits))

        # Walk correlation
        n = min(len(m1.full_walk), len(m2.full_walk))
        if n > 1:
            mean1 = sum(m1.full_walk[:n]) / n
            mean2 = sum(m2.full_walk[:n]) / n
            cov = sum((m1.full_walk[i] - mean1) * (m2.full_walk[i] - mean2) for i in range(n))
            var1 = sum((m1.full_walk[i] - mean1) ** 2 for i in range(n))
            var2 = sum((m2.full_walk[i] - mean2) ** 2 for i in range(n))
            denom = math.sqrt(var1 * var2) if var1 * var2 > 0 else 1.0
            correlation = cov / denom
        else:
            correlation = 0.0

        # Endpoint distance
        endpoint_dist = math.sqrt(
            sum((a - b) ** 2 for a, b in zip(m1.layer_walk_endpoints, m2.layer_walk_endpoints))
        )

        return {
            "hamming_distance": hamming,
            "hamming_ratio": round(hamming / TOTAL_LAYER_BITS, 4),
            "walk_correlation": round(correlation, 6),
            "endpoint_distance": round(endpoint_dist, 4),
            "fibonacci_delta": round(m1.total_fibonacci_score - m2.total_fibonacci_score, 4),
            "quasicrystal_delta": round(m1.quasicrystal_quality - m2.quasicrystal_quality, 4),
            "same_manifold": correlation > 0.7 and hamming / TOTAL_LAYER_BITS < 0.3,
        }

    @property
    def history(self) -> List[BinaryManifold]:
        return list(self._history)
