#!/usr/bin/env python3
"""Build a deterministic dual-nodal manufacturing package with BraidLedger receipt.

One master seed derives separate geometry and signing lanes:
- geometry lane: bounded 256-coefficient ring vector for OpenSCAD geometry
- signing lane: simulated Dilithium-style manifest signature and BraidLedger session key

The BraidLedger integration is intentionally thin glue over ``spiral-word-app``.
It does not introduce a parallel ledger implementation.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[2]
SPIRAL_WORD_APP = REPO_ROOT / "spiral-word-app"
if str(SPIRAL_WORD_APP) not in sys.path:
    sys.path.insert(0, str(SPIRAL_WORD_APP))

from braid_ledger import BraidLedger, BraidReceipt  # type: ignore  # noqa: E402


DEFAULT_MASTER_SEED = b"AETHERMOORE_DUAL_NODAL_PHASE_3A_v1_2026"
DEFAULT_OUTPUT_DIR = REPO_ROOT / "artifacts" / "manufacturing" / "dual_nodal_braid"
COEFFICIENT_COUNT = 256
COEFFICIENT_MIN = -4
COEFFICIENT_MAX = 4


@dataclass(frozen=True)
class ManufacturingPackage:
    """Paths and receipt for a generated manufacturing package."""

    scad_path: Path
    receipt_path: Path
    receipt: dict[str, Any]


class ManufacturingBraidAdapter:
    """Deterministic bridge from one seed to geometry plus governance receipt."""

    def __init__(self, master_seed: bytes, *, timestamp: int | None = None):
        if not master_seed:
            raise ValueError("master_seed must not be empty")
        self.master_seed = master_seed
        self.timestamp = int(time.time() if timestamp is None else timestamp)
        self.geom_seed = self._kdf(b"geometry_polynomials")
        self.sign_seed = self._kdf(b"dilithium_signing_key")

    def _kdf(self, domain: bytes) -> bytes:
        h = hashlib.sha512()
        h.update(b"SCBE-MANUFACTURING-BRAID-v1")
        h.update(b"\x00")
        h.update(self.master_seed)
        h.update(b"\x00")
        h.update(domain)
        return h.digest()

    @property
    def loop_root(self) -> str:
        return hashlib.sha256(self.master_seed).hexdigest()

    def generate_coefficients(self, length: int = COEFFICIENT_COUNT) -> list[int]:
        """Generate bounded Dilithium-style coefficients in [-4, 4]."""

        if length <= 0:
            raise ValueError("length must be positive")
        coeffs: list[int] = []
        data = self.geom_seed
        while len(coeffs) < length:
            data = hashlib.sha512(data).digest()
            for byte in data:
                coeffs.append((byte % 9) - 4)
                if len(coeffs) == length:
                    break
        return coeffs

    def render_openscad(self, coeffs: list[int]) -> str:
        """Render the full dual-nodal OpenSCAD model with coefficients embedded."""

        if len(coeffs) != COEFFICIENT_COUNT:
            raise ValueError(f"expected {COEFFICIENT_COUNT} coefficients")
        if any(c < COEFFICIENT_MIN or c > COEFFICIENT_MAX for c in coeffs):
            raise ValueError("coefficients must be bounded in [-4, 4]")

        coeff_json = json.dumps(coeffs, separators=(",", ":"))
        coeff_hash = hashlib.sha256(coeff_json.encode("ascii")).hexdigest()
        return f"""// SCBE-AETHERMOORE: Dual-Nodal Dynamo Core
// Deterministic manufacturing geometry generated by build_manufacturing_braid_package.py
// coefficient_count = {COEFFICIENT_COUNT}
// coefficient_sha256 = {coeff_hash}

phi = (1 + sqrt(5)) / 2;
golden_angle = 360 / (phi * phi);

R_lobe = 25;
lobe_separation = 18;
t_sheath = 3;
r_throat = 1.5;
c_z = 0.8;
num_ridges = 16;
mesh_height = 70;
node_ball_r_base = 8;

dilithium_coeffs = {coeff_json};

function coeff(i) = dilithium_coeffs[i % len(dilithium_coeffs)];
function coeff_norm(i) = coeff(i) / 4;
function ridge_radius(i) = r_throat + 0.35 * coeff_norm(i);
function node_radius(i) = node_ball_r_base + 0.45 * coeff_norm(i);
function z_for(i, n) = -mesh_height / 2 + (mesh_height * i / max(1, n - 1));

module seeded_ridge(i, side = 1) {{
    angle = i * golden_angle;
    z0 = z_for(i, num_ridges);
    radial = R_lobe + side * 0.6 * coeff_norm(i);
    rotate([0, 0, angle])
        translate([side * radial, 0, z0])
            cylinder(h = mesh_height / num_ridges, r = ridge_radius(i), center = true, $fn = 18);
}}

module nodal_lobe(side = 1) {{
    union() {{
        hull() {{
            translate([side * lobe_separation, 0, -mesh_height / 2])
                sphere(r = node_radius(0), $fn = 42);
            translate([side * (lobe_separation + 3), 0, mesh_height / 2])
                sphere(r = node_radius(127), $fn = 42);
        }}
        for (i = [0 : num_ridges - 1]) seeded_ridge(i + (side > 0 ? 0 : 128), side);
    }}
}}

module coefficient_ring(z = 0) {{
    for (i = [0 : 63]) {{
        angle = i * 360 / 64;
        radius = R_lobe + 4 + 0.25 * coeff_norm(i * 4);
        rotate([0, 0, angle])
            translate([radius, 0, z + coeff_norm(i * 4) * 1.2])
                sphere(r = 0.8 + 0.08 * abs(coeff(i * 4)), $fn = 12);
    }}
}}

module throat_bridge() {{
    hull() {{
        translate([-lobe_separation, 0, 0]) sphere(r = r_throat + t_sheath, $fn = 32);
        translate([ lobe_separation, 0, 0]) sphere(r = r_throat + t_sheath, $fn = 32);
    }}
    rotate([90, 0, 0])
        cylinder(h = 2 * R_lobe, r = r_throat, center = true, $fn = 24);
}}

module dual_nodal_core() {{
    union() {{
        nodal_lobe(-1);
        nodal_lobe(1);
        throat_bridge();
        coefficient_ring(-mesh_height / 4);
        coefficient_ring(mesh_height / 4);
    }}
}}

dual_nodal_core();
"""

    def sign_manifest(self, part_name: str, scad_path: Path, coeffs: list[int]) -> dict[str, Any]:
        """Create a signed manifest plus a real BraidLedger receipt."""

        scad_bytes = scad_path.read_bytes()
        scad_hash = hashlib.sha256(scad_bytes).hexdigest()
        coeff_json = json.dumps(coeffs, separators=(",", ":"))
        coeff_hash = hashlib.sha256(coeff_json.encode("ascii")).hexdigest()

        manifest_payload = {
            "part_name": part_name,
            "scad_sha256": scad_hash,
            "coeff_sha256": coeff_hash,
            "timestamp": self.timestamp,
        }
        manifest_bytes = json.dumps(manifest_payload, sort_keys=True, separators=(",", ":")).encode("utf-8")

        sig_hash = hashlib.sha3_512()
        sig_hash.update(self.sign_seed)
        sig_hash.update(manifest_bytes)
        signature = sig_hash.hexdigest()

        ledger = BraidLedger(session_key=self.sign_seed[:32])
        braid_receipt: BraidReceipt = ledger.commit(
            prompt_hash=hashlib.sha256(part_name.encode("utf-8")).hexdigest(),
            docx_hash=scad_hash,
        )
        chain_ok, tube_ok, bad_idx = ledger.verify([braid_receipt])

        return {
            "schema_version": "scbe_manufacturing_braid_package_v1",
            "part_id": f"SCBE-{hashlib.sha256(self.master_seed).hexdigest()[:8].upper()}",
            "part_name": part_name,
            "generated_at_unix": self.timestamp,
            "scad_sha256": scad_hash,
            "coeff_sha256": coeff_hash,
            "coefficient_count": len(coeffs),
            "coefficient_bounds": [COEFFICIENT_MIN, COEFFICIENT_MAX],
            "seed_commitments": {
                "master_seed_sha256": hashlib.sha256(self.master_seed).hexdigest(),
                "geom_seed_sha256": hashlib.sha256(self.geom_seed).hexdigest(),
                "sign_seed_sha256": hashlib.sha256(self.sign_seed).hexdigest(),
            },
            "signature": {
                "framework": "CRYSTALS-Dilithium-style-simulated",
                "domain": "dilithium_signing_key",
                "manifest_payload_sha256": hashlib.sha256(manifest_bytes).hexdigest(),
                "signature_sha3_512": signature,
            },
            "braid_receipt": asdict(braid_receipt),
            "braid_verification": {
                "chain_ok": chain_ok,
                "tube_ok": tube_ok,
                "bad_index": bad_idx,
            },
        }

    def export_full_package(
        self,
        output_dir: Path,
        *,
        part_name: str = "Dual-Nodal Dynamo Core",
    ) -> ManufacturingPackage:
        """Generate OpenSCAD and signed receipt files."""

        output_dir.mkdir(parents=True, exist_ok=True)
        coeffs = self.generate_coefficients()
        scad_path = output_dir / "dynamo_core_dual_nodal_dilithium.scad"
        receipt_path = output_dir / "braidledger_receipt.json"

        scad_path.write_text(self.render_openscad(coeffs), encoding="utf-8")
        receipt = self.sign_manifest(part_name, scad_path, coeffs)
        receipt_path.write_text(json.dumps(receipt, indent=2, sort_keys=True), encoding="utf-8")
        return ManufacturingPackage(scad_path=scad_path, receipt_path=receipt_path, receipt=receipt)


def _seed_from_args(args: argparse.Namespace) -> bytes:
    if args.master_seed_hex:
        return bytes.fromhex(args.master_seed_hex)
    if args.master_seed:
        return args.master_seed.encode("utf-8")
    return DEFAULT_MASTER_SEED


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--master-seed", default="", help="UTF-8 master seed. Defaults to deterministic demo seed.")
    parser.add_argument("--master-seed-hex", default="", help="Hex master seed. Overrides --master-seed.")
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--part-name", default="Dual-Nodal Dynamo Core")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    adapter = ManufacturingBraidAdapter(_seed_from_args(args))
    package = adapter.export_full_package(args.output_dir, part_name=args.part_name)
    print(f"Generated SCAD: {package.scad_path}")
    print(f"Receipt JSON:   {package.receipt_path}")
    print(f"Part ID:        {package.receipt['part_id']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
