#!/usr/bin/env python3
"""Generate a SELF-CONTAINED Kaggle kernel that benchmarks the Rust AST cube
encoder vs the Python reference on Kaggle's (quiet) free compute.

Mirrors scripts/kaggle_auto/*: base64-embed every input (Rust crate source +
Python reference encoder + a Python corpus) into one script kernel, so there is
no dataset upload and no repo clone. The kernel builds Rust on Kaggle Linux, then
runs the same methodology as scripts/benchmarks/encoder_bench.py and writes a
filled score card to /kaggle/working/.

Run:  python scripts/kaggle/build_encoder_kernel.py
Then: cd scripts/kaggle/encoder_bench && kaggle kernels push
"""

from __future__ import annotations

import base64
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT_DIR = ROOT / "scripts" / "kaggle" / "encoder_bench"
KERNEL_ID = "issacizrealdavis/scbe-ast-encoder-benchmark"
CORPUS_LIMIT = 12

KERNEL_TEMPLATE = '''#!/usr/bin/env python3
"""SELF-CONTAINED Kaggle kernel: Rust AST cube encoder vs Python reference.

Auto-generated by scripts/kaggle/build_encoder_kernel.py. Builds the embedded
Rust crate on Kaggle, then times it against the embedded Python reference encoder
over an embedded corpus with warmup + repeated runs, and writes a score card
(research/benchmarks/score-template.json shape) to /kaggle/working/.
"""
import base64
import importlib.util
import json
import math
import os
import platform
import shutil
import statistics
import subprocess
import sys
import time
from pathlib import Path

EMB = "__BLOB__"
FILES = json.loads(base64.b64decode(EMB).decode("utf-8"))

WORK = Path("/kaggle/working")
ROOT = WORK / "bench"
(ROOT / "src").mkdir(parents=True, exist_ok=True)
(ROOT / "Cargo.toml").write_text(FILES["cargo_toml"], encoding="utf-8")
(ROOT / "Cargo.lock").write_text(FILES["cargo_lock"], encoding="utf-8")
(ROOT / "src" / "main.rs").write_text(FILES["main_rs"], encoding="utf-8")
corpus_dir = ROOT / "corpus"
corpus_dir.mkdir(exist_ok=True)
corpus = []
for name, content in FILES["corpus"].items():
    p = corpus_dir / name
    p.write_text(content, encoding="utf-8")
    corpus.append(p)
corpus.sort()
loc = sum(len(p.read_text(encoding="utf-8", errors="surrogatepass").splitlines()) for p in corpus)

enc_path = ROOT / "ast_cube_encoder.py"
enc_path.write_text(FILES["encoder_py"], encoding="utf-8")
spec = importlib.util.spec_from_file_location("ast_cube_encoder", enc_path)
encoder = importlib.util.module_from_spec(spec)
spec.loader.exec_module(encoder)

# --- build Rust on Kaggle (install toolchain if absent) ---
cargo = shutil.which("cargo")
if not cargo:
    print("installing rust toolchain ...", flush=True)
    subprocess.run(
        "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal",
        shell=True, check=True,
    )
    os.environ["PATH"] = os.path.expanduser("~/.cargo/bin") + os.pathsep + os.environ["PATH"]
    cargo = shutil.which("cargo") or os.path.expanduser("~/.cargo/bin/cargo")

build_start = time.time()
subprocess.run([cargo, "build", "--release", "--manifest-path", str(ROOT / "Cargo.toml")], check=True)
build_s = round(time.time() - build_start, 1)
exe = ROOT / "target" / "release" / "ast_cube"
print("rust build:", build_s, "s; exe:", exe.exists(), flush=True)

WARMUP, RUNS, PURE_RUNS, BIG_TARGET, CV_WARN = 5, 20, 10, 200, 5.0


def run_python(files):
    start = time.perf_counter()
    for path in files:
        encoder.encode_matrix(path.read_text(encoding="utf-8", errors="surrogatepass"))
    return time.perf_counter() - start


def run_rust(files):
    start = time.perf_counter()
    subprocess.run([str(exe), "--binary", *[str(f) for f in files]], check=True, capture_output=True)
    return time.perf_counter() - start


def measure(fn, files, runs, warmup):
    for _ in range(warmup):
        fn(files)
    return [fn(files) for _ in range(runs)]


def summarize(times):
    mean = statistics.fmean(times)
    stdev = statistics.stdev(times) if len(times) > 1 else 0.0
    n = len(times)
    half = 1.96 * stdev / math.sqrt(n) if n > 1 else 0.0
    return {
        "runs": n, "mean": round(mean, 6), "median": round(statistics.median(times), 6),
        "stddev": round(stdev, 6), "min": round(min(times), 6), "max": round(max(times), 6),
        "cv_pct": round((stdev / mean) * 100, 3) if mean else 0.0,
        "ci95": [round(mean - half, 6), round(mean + half, 6)], "unit": "s",
    }


py = summarize(measure(run_python, corpus, RUNS, WARMUP))
rust = summarize(measure(run_rust, corpus, RUNS, WARMUP))
e2e_speedup = round(py["median"] / rust["median"], 2) if rust["median"] else None

big = (corpus * max(1, math.ceil(BIG_TARGET / len(corpus))))[:BIG_TARGET]
r1 = statistics.median(measure(run_rust, corpus[:1], PURE_RUNS, WARMUP))
rN = statistics.median(measure(run_rust, big, PURE_RUNS, WARMUP))
rust_per_file = (rN - r1) / (len(big) - 1) if len(big) > 1 else rN
rust_startup = r1 - rust_per_file
py_big = summarize(measure(run_python, big, PURE_RUNS, WARMUP))
py_per_file = py_big["median"] / len(big)
engine_speedup = round(py_per_file / rust_per_file, 2) if rust_per_file > 0 else None

card = {
    "schema_version": "scbe_benchmark_score_v1",
    "benchmark": "ast-cube-encoder",
    "goal": "comparison",
    "metric": {"name": "wall_time", "unit": "s", "lower_is_better": True,
               "definition": "end-to-end encode of corpus; Python in-process, Rust one subprocess incl startup"},
    "variants": {"python_reference": py, "rust": rust},
    "end_to_end_speedup_x": e2e_speedup,
    "pure_encode": {
        "method": "two-point linear model t(k)=startup+k*per_file; subprocess startup excluded",
        "batch_files": len(big),
        "rust_startup_ms": round(rust_startup * 1000, 3),
        "rust_per_file_ms": round(rust_per_file * 1000, 4),
        "python_per_file_ms": round(py_per_file * 1000, 4),
        "engine_speedup_x": engine_speedup,
        "python_batch_cv_pct": py_big["cv_pct"],
        "reliable": rust_per_file > 0 and py_big["cv_pct"] < CV_WARN,
    },
    "input": {"description": "embedded python/scbe corpus", "size": f"{len(corpus)} files / {loc} LOC", "seed": 0},
    "environment": {
        "cpu": platform.processor() or platform.machine(),
        "cores": os.cpu_count() or 0,
        "os": f"{platform.system()} {platform.release()}",
        "runtime": f"python {platform.python_version()}",
        "toolchain_versions": {"rust_build_seconds": build_s},
        "machine_class": "kaggle",
        "cpu_governor": "kaggle-managed",
    },
    "tool": "custom (perf_counter, stdlib statistics)",
    "stable": py["cv_pct"] < CV_WARN and rust["cv_pct"] < CV_WARN,
    "notes": "Kaggle free compute. Rust path includes subprocess startup; engine_speedup is startup-excluded.",
}
(WORK / "encoder-card.json").write_text(json.dumps(card, indent=2), encoding="utf-8")
print(json.dumps(card, indent=2))
print(f"\\nSUMMARY corpus {len(corpus)}f/{loc}LOC | py {py['median']*1000:.1f}ms CV{py['cv_pct']}% | "
      f"rust {rust['median']*1000:.1f}ms CV{rust['cv_pct']}% | e2e {e2e_speedup}x | engine {engine_speedup}x")
'''


def main() -> int:
    crate = ROOT / "rust" / "ast_cube"
    encoder_py = ROOT / "python" / "scbe" / "ast_cube_encoder.py"
    corpus_files = sorted((ROOT / "python" / "scbe").glob("*.py"))
    corpus_files = [f for f in corpus_files if f.name != "__init__.py"][:CORPUS_LIMIT]

    emb = {
        "cargo_toml": (crate / "Cargo.toml").read_text(encoding="utf-8"),
        "cargo_lock": (crate / "Cargo.lock").read_text(encoding="utf-8"),
        "main_rs": (crate / "src" / "main.rs").read_text(encoding="utf-8"),
        "encoder_py": encoder_py.read_text(encoding="utf-8"),
        "corpus": {f.name: f.read_text(encoding="utf-8", errors="surrogatepass") for f in corpus_files},
    }
    blob = base64.b64encode(json.dumps(emb).encode("utf-8")).decode("ascii")
    kernel = KERNEL_TEMPLATE.replace("__BLOB__", blob)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "encoder_bench_kernel.py").write_text(kernel, encoding="utf-8")
    metadata = {
        "id": KERNEL_ID,
        "title": "SCBE AST Encoder Benchmark",
        "code_file": "encoder_bench_kernel.py",
        "language": "python",
        "kernel_type": "script",
        "is_private": "true",
        "enable_gpu": "false",
        "enable_internet": "true",
        "dataset_sources": [],
        "competition_sources": [],
        "kernel_sources": [],
    }
    (OUT_DIR / "kernel-metadata.json").write_text(json.dumps(metadata, indent=1), encoding="utf-8")
    size_kb = (OUT_DIR / "encoder_bench_kernel.py").stat().st_size / 1024
    print(f"wrote {OUT_DIR/'encoder_bench_kernel.py'} ({size_kb:.0f} KB, {len(corpus_files)} corpus files)")
    print(f"push with: cd {OUT_DIR} && kaggle kernels push")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
