#!/usr/bin/env python3
"""Generate a sorted skill index for the repo-local skills directory.

This is documentation tooling only (no runtime behavior impact).
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re
from typing import List


ROOT = Path(__file__).resolve().parent.parent
SKILLS_DIR = ROOT / "skills"
OUT_PATH = SKILLS_DIR / "SKILLS_INDEX.md"


@dataclass
class SkillMeta:
    name: str
    description: str
    rel_path: str


def _parse_frontmatter(text: str) -> tuple[str, str]:
    if not text.startswith("---\n"):
        return "", ""

    end = text.find("\n---\n", 4)
    if end < 0:
        return "", ""

    block = text[4:end]
    name_match = re.search(r"^name:\s*(.+)$", block, flags=re.MULTILINE)
    desc_match = re.search(r"^description:\s*(.+)$", block, flags=re.MULTILINE)

    name = name_match.group(1).strip() if name_match else ""
    desc = desc_match.group(1).strip() if desc_match else ""
    return name, desc


def collect_skills() -> List[SkillMeta]:
    rows: List[SkillMeta] = []
    if not SKILLS_DIR.exists():
        return rows

    for path in sorted(SKILLS_DIR.rglob("SKILL.md")):
        content = path.read_text(encoding="utf-8", errors="replace")
        name, desc = _parse_frontmatter(content)
        if not name:
            name = path.parent.name
        if not desc:
            desc = "(missing frontmatter description)"
        rel_path = str(path.relative_to(ROOT)).replace("\\", "/")
        rows.append(SkillMeta(name=name, description=desc, rel_path=rel_path))

    rows.sort(key=lambda x: x.name.lower())
    return rows


def write_index(rows: List[SkillMeta]) -> None:
    lines = [
        "# Skills Index",
        "",
        "Auto-generated by `scripts/sort_skills_index.py`.",
        "",
        "| Skill | Description | Path |",
        "|---|---|---|",
    ]

    for row in rows:
        lines.append(f"| `{row.name}` | {row.description} | `{row.rel_path}` |")

    OUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    rows = collect_skills()
    write_index(rows)
    print(f"Wrote {OUT_PATH} with {len(rows)} skills")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
