import type { AppDefinition } from '@/types';

export function generateAppRegistry(): Map<string, AppDefinition> {
  const registry = new Map<string, AppDefinition>();

  const apps: AppDefinition[] = [
    // === SYSTEM & PRODUCTIVITY ===
    {
      id: 'files',
      name: 'File Manager',
      icon: 'FolderOpen',
      category: 'System',
      component: null as any,
      defaultSize: { width: 800, height: 500 },
      minSize: { width: 400, height: 300 },
    },
    {
      id: 'terminal',
      name: 'Terminal',
      icon: 'Terminal',
      category: 'System',
      component: null as any,
      defaultSize: { width: 700, height: 450 },
      minSize: { width: 400, height: 300 },
    },
    {
      id: 'multiagent',
      name: 'Multi-Agent Terminal',
      icon: 'Bot',
      category: 'Development',
      component: null as any,
      defaultSize: { width: 800, height: 550 },
      minSize: { width: 500, height: 400 },
    },
    {
      id: 'texteditor',
      name: 'Text Editor',
      icon: 'FileText',
      category: 'Productivity',
      component: null as any,
      defaultSize: { width: 700, height: 500 },
      minSize: { width: 400, height: 300 },
    },
    {
      id: 'browser',
      name: 'Browser',
      icon: 'Globe',
      category: 'Internet',
      component: null as any,
      defaultSize: { width: 900, height: 600 },
      minSize: { width: 500, height: 400 },
    },
    {
      id: 'calculator',
      name: 'Calculator',
      icon: 'Calculator',
      category: 'Utilities',
      component: null as any,
      defaultSize: { width: 340, height: 480 },
      minSize: { width: 340, height: 480 },
      canResize: false,
    },
    {
      id: 'settings',
      name: 'Settings',
      icon: 'Settings',
      category: 'System',
      component: null as any,
      defaultSize: { width: 700, height: 500 },
      minSize: { width: 500, height: 400 },
      singleton: true,
    },
    {
      id: 'calendar',
      name: 'Calendar',
      icon: 'Calendar',
      category: 'Productivity',
      component: null as any,
      defaultSize: { width: 600, height: 500 },
      minSize: { width: 400, height: 350 },
    },
    {
      id: 'clock',
      name: 'Clock',
      icon: 'Clock',
      category: 'Utilities',
      component: null as any,
      defaultSize: { width: 400, height: 300 },
      minSize: { width: 350, height: 250 },
    },
    {
      id: 'taskmanager',
      name: 'Task Manager',
      icon: 'Activity',
      category: 'System',
      component: null as any,
      defaultSize: { width: 700, height: 500 },
      minSize: { width: 500, height: 400 },
      singleton: true,
    },
    {
      id: 'search',
      name: 'Search',
      icon: 'Search',
      category: 'System',
      component: null as any,
      defaultSize: { width: 600, height: 450 },
      minSize: { width: 400, height: 300 },
      canResize: false,
    },
    // === GAMES (15) ===
    {
      id: 'snake',
      name: 'Snake',
      icon: 'Gamepad2',
      category: 'Games',
      component: null as any,
      defaultSize: { width: 520, height: 560 },
      minSize: { width: 520, height: 560 },
      canResize: false,
    },
    {
      id: 'tetris',
      name: 'Tetris',
      icon: 'Grid3x3',
      category: 'Games',
      component: null as any,
      defaultSize: { width: 400, height: 600 },
      minSize: { width: 400, height: 600 },
      canResize: false,
    },
    {
      id: 'minesweeper',
      name: 'Minesweeper',
      icon: 'Bomb',
      category: 'Games',
      component: null as any,
      defaultSize: { width: 400, height: 480 },
      minSize: { width: 400, height: 480 },
      canResize: false,
    },
    {
      id: 'tictactoe',
      name: 'Tic Tac Toe',
      icon: 'XCircle',
      category: 'Games',
      component: null as any,
      defaultSize: { width: 400, height: 480 },
      minSize: { width: 400, height: 480 },
      canResize: false,
    },
    {
      id: 'pong',
      name: 'Pong',
      icon: 'MonitorPlay',
      category: 'Games',
      component: null as any,
      defaultSize: { width: 700, height: 450 },
      minSize: { width: 700, height: 450 },
      canResize: false,
    },
    {
      id: 'breakout',
      name: 'Breakout',
      icon: 'RectangleHorizontal',
      category: 'Games',
      component: null as any,
      defaultSize: { width: 640, height: 500 },
      minSize: { width: 640, height: 500 },
      canResize: false,
    },
    {
      id: 'memory',
      name: 'Memory Match',
      icon: 'Brain',
      category: 'Games',
      component: null as any,
      defaultSize: { width: 560, height: 560 },
      minSize: { width: 560, height: 560 },
      canResize: false,
    },
    {
      id: 'sudoku',
      name: 'Sudoku',
      icon: 'Grid2x2',
      category: 'Games',
      component: null as any,
      defaultSize: { width: 500, height: 580 },
      minSize: { width: 500, height: 580 },
      canResize: false,
    },
    {
      id: 'chess',
      name: 'Chess',
      icon: 'Crown',
      category: 'Games',
      component: null as any,
      defaultSize: { width: 560, height: 620 },
      minSize: { width: 560, height: 620 },
      canResize: false,
    },
    {
      id: 'wordle',
      name: 'Wordle',
      icon: 'Type',
      category: 'Games',
      component: null as any,
      defaultSize: { width: 450, height: 650 },
      minSize: { width: 450, height: 650 },
      canResize: false,
    },
    {
      id: 'game2048',
      name: '2048',
      icon: 'Divide',
      category: 'Games',
      component: null as any,
      defaultSize: { width: 430, height: 560 },
      minSize: { width: 430, height: 560 },
      canResize: false,
    },
    {
      id: 'dinorun',
      name: 'Dino Run',
      icon: 'Footprints',
      category: 'Games',
      component: null as any,
      defaultSize: { width: 700, height: 250 },
      minSize: { width: 700, height: 250 },
      canResize: false,
    },
    {
      id: 'flappybird',
      name: 'Flappy Bird',
      icon: 'Bird',
      category: 'Games',
      component: null as any,
      defaultSize: { width: 420, height: 600 },
      minSize: { width: 420, height: 600 },
      canResize: false,
    },
    {
      id: 'solitaire',
      name: 'Solitaire',
      icon: 'Layers',
      category: 'Games',
      component: null as any,
      defaultSize: { width: 750, height: 550 },
      minSize: { width: 750, height: 550 },
      canResize: false,
    },
    {
      id: 'hangman',
      name: 'Hangman',
      icon: 'UserX',
      category: 'Games',
      component: null as any,
      defaultSize: { width: 500, height: 500 },
      minSize: { width: 500, height: 500 },
      canResize: false,
    },
    // === MEDIA ===
    {
      id: 'musicplayer',
      name: 'Music Player',
      icon: 'Music',
      category: 'Media',
      component: null as any,
      defaultSize: { width: 450, height: 600 },
      minSize: { width: 400, height: 500 },
    },
    {
      id: 'photoviewer',
      name: 'Photo Viewer',
      icon: 'Image',
      category: 'Media',
      component: null as any,
      defaultSize: { width: 700, height: 500 },
      minSize: { width: 400, height: 300 },
    },
    {
      id: 'drawing',
      name: 'Paint',
      icon: 'Paintbrush',
      category: 'Media',
      component: null as any,
      defaultSize: { width: 800, height: 600 },
      minSize: { width: 500, height: 400 },
    },
    {
      id: 'camera',
      name: 'Camera',
      icon: 'Camera',
      category: 'Media',
      component: null as any,
      defaultSize: { width: 500, height: 450 },
      minSize: { width: 400, height: 350 },
    },
    {
      id: 'videoplayer',
      name: 'Video Player',
      icon: 'Video',
      category: 'Media',
      component: null as any,
      defaultSize: { width: 700, height: 450 },
      minSize: { width: 400, height: 300 },
    },
    // === PRODUCTIVITY ===
    {
      id: 'notes',
      name: 'Notes',
      icon: 'StickyNote',
      category: 'Productivity',
      component: null as any,
      defaultSize: { width: 500, height: 500 },
      minSize: { width: 350, height: 350 },
    },
    {
      id: 'spreadsheet',
      name: 'Spreadsheet',
      icon: 'Table',
      category: 'Productivity',
      component: null as any,
      defaultSize: { width: 800, height: 550 },
      minSize: { width: 500, height: 400 },
    },
    {
      id: 'todo',
      name: 'Todo List',
      icon: 'CheckSquare',
      category: 'Productivity',
      component: null as any,
      defaultSize: { width: 450, height: 550 },
      minSize: { width: 350, height: 400 },
    },
    {
      id: 'pdfviewer',
      name: 'PDF Viewer',
      icon: 'FileType',
      category: 'Productivity',
      component: null as any,
      defaultSize: { width: 700, height: 600 },
      minSize: { width: 400, height: 400 },
    },
    {
      id: 'voicerecorder',
      name: 'Voice Recorder',
      icon: 'Mic',
      category: 'Productivity',
      component: null as any,
      defaultSize: { width: 400, height: 300 },
      minSize: { width: 350, height: 250 },
    },
    {
      id: 'reminders',
      name: 'Reminders',
      icon: 'Bell',
      category: 'Productivity',
      component: null as any,
      defaultSize: { width: 450, height: 500 },
      minSize: { width: 350, height: 400 },
    },
    // === DEV TOOLS ===
    {
      id: 'codeeditor',
      name: 'Code Editor',
      icon: 'Code',
      category: 'Development',
      component: null as any,
      defaultSize: { width: 850, height: 600 },
      minSize: { width: 500, height: 400 },
    },
    {
      id: 'jsonformatter',
      name: 'JSON Formatter',
      icon: 'Braces',
      category: 'Development',
      component: null as any,
      defaultSize: { width: 700, height: 500 },
      minSize: { width: 450, height: 350 },
    },
    {
      id: 'regextester',
      name: 'Regex Tester',
      icon: 'Regex',
      category: 'Development',
      component: null as any,
      defaultSize: { width: 650, height: 480 },
      minSize: { width: 450, height: 350 },
    },
    {
      id: 'markdownpreview',
      name: 'Markdown',
      icon: 'FileCode',
      category: 'Development',
      component: null as any,
      defaultSize: { width: 800, height: 600 },
      minSize: { width: 450, height: 400 },
    },
    {
      id: 'htmleditor',
      name: 'HTML Editor',
      icon: 'FileJson',
      category: 'Development',
      component: null as any,
      defaultSize: { width: 900, height: 600 },
      minSize: { width: 500, height: 400 },
    },
    {
      id: 'colorpicker',
      name: 'Color Picker',
      icon: 'Palette',
      category: 'Utilities',
      component: null as any,
      defaultSize: { width: 450, height: 400 },
      minSize: { width: 400, height: 350 },
    },
    {
      id: 'passwordgen',
      name: 'Password Generator',
      icon: 'KeyRound',
      category: 'Utilities',
      component: null as any,
      defaultSize: { width: 450, height: 400 },
      minSize: { width: 400, height: 350 },
    },
    // === UTILITIES ===
    {
      id: 'stopwatch',
      name: 'Stopwatch',
      icon: 'Timer',
      category: 'Utilities',
      component: null as any,
      defaultSize: { width: 400, height: 300 },
      minSize: { width: 350, height: 250 },
    },
    {
      id: 'timer',
      name: 'Timer',
      icon: 'Hourglass',
      category: 'Utilities',
      component: null as any,
      defaultSize: { width: 400, height: 350 },
      minSize: { width: 350, height: 300 },
    },
    {
      id: 'weather',
      name: 'Weather',
      icon: 'CloudSun',
      category: 'Utilities',
      component: null as any,
      defaultSize: { width: 450, height: 500 },
      minSize: { width: 350, height: 400 },
    },
    {
      id: 'unitconverter',
      name: 'Unit Converter',
      icon: 'ArrowLeftRight',
      category: 'Utilities',
      component: null as any,
      defaultSize: { width: 450, height: 500 },
      minSize: { width: 400, height: 400 },
    },
    {
      id: 'qrcode',
      name: 'QR Code Generator',
      icon: 'QrCode',
      category: 'Utilities',
      component: null as any,
      defaultSize: { width: 450, height: 500 },
      minSize: { width: 400, height: 450 },
    },
    {
      id: 'translator',
      name: 'Translator',
      icon: 'Languages',
      category: 'Utilities',
      component: null as any,
      defaultSize: { width: 550, height: 450 },
      minSize: { width: 400, height: 350 },
    },
    {
      id: 'systemmonitor',
      name: 'System Monitor',
      icon: 'BarChart3',
      category: 'System',
      component: null as any,
      defaultSize: { width: 700, height: 500 },
      minSize: { width: 500, height: 400 },
      singleton: true,
    },
    {
      id: 'diskusage',
      name: 'Disk Usage',
      icon: 'HardDrive',
      category: 'System',
      component: null as any,
      defaultSize: { width: 600, height: 450 },
      minSize: { width: 400, height: 350 },
    },
    // === INTERNET ===
    {
      id: 'mail',
      name: 'Mail',
      icon: 'Mail',
      category: 'Internet',
      component: null as any,
      defaultSize: { width: 800, height: 550 },
      minSize: { width: 500, height: 400 },
    },
    {
      id: 'chat',
      name: 'Chat',
      icon: 'MessageCircle',
      category: 'Internet',
      component: null as any,
      defaultSize: { width: 500, height: 550 },
      minSize: { width: 350, height: 450 },
    },
    {
      id: 'contacts',
      name: 'Contacts',
      icon: 'Contact',
      category: 'Internet',
      component: null as any,
      defaultSize: { width: 500, height: 500 },
      minSize: { width: 400, height: 400 },
    },
    {
      id: 'news',
      name: 'News Reader',
      icon: 'Newspaper',
      category: 'Internet',
      component: null as any,
      defaultSize: { width: 700, height: 550 },
      minSize: { width: 450, height: 400 },
    },
    {
      id: 'stocks',
      name: 'Stocks',
      icon: 'TrendingUp',
      category: 'Internet',
      component: null as any,
      defaultSize: { width: 650, height: 500 },
      minSize: { width: 450, height: 400 },
    },
    // === FUN & EXTRA ===
    {
      id: 'paint',
      name: 'Paint Pro',
      icon: 'PaintBucket',
      category: 'Media',
      component: null as any,
      defaultSize: { width: 850, height: 650 },
      minSize: { width: 500, height: 400 },
    },
    {
      id: 'wiki',
      name: 'Wiki Browser',
      icon: 'BookOpen',
      category: 'Internet',
      component: null as any,
      defaultSize: { width: 800, height: 600 },
      minSize: { width: 500, height: 400 },
    },
    {
      id: 'rssreader',
      name: 'RSS Reader',
      icon: 'Rss',
      category: 'Internet',
      component: null as any,
      defaultSize: { width: 700, height: 550 },
      minSize: { width: 450, height: 400 },
    },
    {
      id: 'whiteboard',
      name: 'Whiteboard',
      icon: 'Pencil',
      category: 'Productivity',
      component: null as any,
      defaultSize: { width: 900, height: 650 },
      minSize: { width: 500, height: 400 },
    },
    {
      id: 'dictionary',
      name: 'Dictionary',
      icon: 'BookMarked',
      category: 'Utilities',
      component: null as any,
      defaultSize: { width: 500, height: 450 },
      minSize: { width: 400, height: 350 },
    },
    {
      id: 'hashgenerator',
      name: 'Hash Generator',
      icon: 'Fingerprint',
      category: 'Utilities',
      component: null as any,
      defaultSize: { width: 500, height: 400 },
      minSize: { width: 400, height: 350 },
    },
    {
      id: 'diffchecker',
      name: 'Diff Checker',
      icon: 'GitCompare',
      category: 'Development',
      component: null as any,
      defaultSize: { width: 800, height: 550 },
      minSize: { width: 500, height: 400 },
    },
    {
      id: 'binaryclock',
      name: 'Binary Clock',
      icon: 'Binary',
      category: 'Utilities',
      component: null as any,
      defaultSize: { width: 450, height: 300 },
      minSize: { width: 400, height: 250 },
    },
    {
      id: 'calculatorpro',
      name: 'Scientific Calc',
      icon: 'Sigma',
      category: 'Utilities',
      component: null as any,
      defaultSize: { width: 450, height: 580 },
      minSize: { width: 450, height: 580 },
      canResize: false,
    },
    {
      id: 'mathgraph',
      name: 'Math Graph',
      icon: 'GitGraph',
      category: 'Utilities',
      component: null as any,
      defaultSize: { width: 800, height: 600 },
      minSize: { width: 600, height: 450 },
    },
    {
      id: 'bmi',
      name: 'BMI Calculator',
      icon: 'HeartPulse',
      category: 'Utilities',
      component: null as any,
      defaultSize: { width: 400, height: 450 },
      minSize: { width: 350, height: 400 },
      canResize: false,
    },
    {
      id: 'typeracer',
      name: 'Type Racer',
      icon: 'Keyboard',
      category: 'Games',
      component: null as any,
      defaultSize: { width: 700, height: 400 },
      minSize: { width: 600, height: 350 },
      canResize: false,
    },
    {
      id: 'connect4',
      name: 'Connect 4',
      icon: 'CircleDot',
      category: 'Games',
      component: null as any,
      defaultSize: { width: 560, height: 520 },
      minSize: { width: 560, height: 520 },
      canResize: false,
    },
    {
      id: 'reversi',
      name: 'Reversi',
      icon: 'RotateCcw',
      category: 'Games',
      component: null as any,
      defaultSize: { width: 520, height: 580 },
      minSize: { width: 520, height: 580 },
      canResize: false,
    },
    {
      id: 'blackjack',
      name: 'Blackjack',
      icon: 'Club',
      category: 'Games',
      component: null as any,
      defaultSize: { width: 650, height: 500 },
      minSize: { width: 650, height: 500 },
      canResize: false,
    },
    {
      id: 'quiz',
      name: 'Trivia Quiz',
      icon: 'HelpCircle',
      category: 'Games',
      component: null as any,
      defaultSize: { width: 550, height: 500 },
      minSize: { width: 450, height: 400 },
      canResize: false,
    },
    {
      id: 'benchmark',
      name: 'Benchmark',
      icon: 'Gauge',
      category: 'System',
      component: null as any,
      defaultSize: { width: 600, height: 450 },
      minSize: { width: 400, height: 350 },
      singleton: true,
    },
    {
      id: 'network',
      name: 'Network Tools',
      icon: 'Network',
      category: 'System',
      component: null as any,
      defaultSize: { width: 650, height: 480 },
      minSize: { width: 450, height: 350 },
    },
    {
      id: 'presentation',
      name: 'Presentation',
      icon: 'Presentation',
      category: 'Productivity',
      component: null as any,
      defaultSize: { width: 850, height: 600 },
      minSize: { width: 500, height: 400 },
    },
    // === ECOSYSTEM: AGENTIC GOVERNANCE ===
    {
      id: 'governance',
      name: 'Governance Console',
      icon: 'Shield',
      category: 'Ecosystem',
      component: null as any,
      defaultSize: { width: 900, height: 600 },
      minSize: { width: 600, height: 450 },
      singleton: true,
    },
    {
      id: 'modelrouter',
      name: 'Model Router',
      icon: 'Cpu',
      category: 'Ecosystem',
      component: null as any,
      defaultSize: { width: 800, height: 550 },
      minSize: { width: 500, height: 400 },
      singleton: true,
    },
    {
      id: 'execution',
      name: 'Execution Timeline',
      icon: 'GitBranch',
      category: 'Ecosystem',
      component: null as any,
      defaultSize: { width: 900, height: 600 },
      minSize: { width: 600, height: 450 },
      singleton: true,
    },
    {
      id: 'auditlogs',
      name: 'Audit Logs',
      icon: 'Fingerprint',
      category: 'Ecosystem',
      component: null as any,
      defaultSize: { width: 850, height: 550 },
      minSize: { width: 550, height: 400 },
      singleton: true,
    },
    {
      id: 'approvalgates',
      name: 'Approval Gates',
      icon: 'ShieldCheck',
      category: 'Ecosystem',
      component: null as any,
      defaultSize: { width: 800, height: 550 },
      minSize: { width: 500, height: 400 },
      singleton: true,
    },
  ];

  apps.forEach((app) => registry.set(app.id, app));
  return registry;
}
